### ISSUE TITLE
Better nodejs tracing

### ISSUE THREAD

**Issue by fetsorn** [Web3-API/prototype#1048]
The Polywrap client has good foundations for tracing, but it needs better filters and easier setup. 

CLI should have a `polywrap trace` command, which would spin up a docker container with SigNoz and OpenTelemetry Collector.

# Signoz 
 - provides detailed tracing UI  
 - has powerful filters
 - exports detailed metadata already provided by the console tracer
 - filters traces by function arguments. 
   - Only string arguments for now, support for objects should be added in signoz/signoz#1397
<details>
  <summary>There's screenshots under the thing</summary>

![](https://cdn.discordapp.com/attachments/989688893001580544/997106762647871509/Screen_Shot_2022-07-14_at_15.31.16.png)

![](https://cdn.discordapp.com/attachments/989688893001580544/997108431431413800/Screen_Shot_2022-07-14_at_15.49.27.png)

![](https://cdn.discordapp.com/attachments/989688893001580544/997116204009406554/Screen_Shot_2022-07-14_at_15.55.02.png)

![](https://cdn.discordapp.com/attachments/989688893001580544/997116204328161301/Screen_Shot_2022-07-14_at_16.20.29.png)
</details>

**Comment by dOrgJelli** [comment]
Hey @fetsorn, would you call this work completed? The desired changes seem to have been released here: https://github.com/polywrap/toolchain/releases/tag/0.5.0

**Comment by fetsorn** [comment]
Yes, this is completed.
