### ISSUE TITLE
Bug: deployment pipeline -> ipfs deployment -> 413 Request Entity Too Large

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1061]
When trying to deploy the Uniswap V3 wrapper, I got this error. Deleting the `meta` folder and `polywrap.meta.json` resolved the issue.

<img width="1440" alt="Screen Shot 2022-07-21 at 1 05 54 PM" src="https://user-images.githubusercontent.com/39842820/180188658-ffb47c2b-6dac-46d1-a275-e72926d6f8f9.png">

**Comment by cbrzn** [comment]
@nerfZael probably is something related to the constraints defined in wrappers.io regarding package validation?

**Comment by nerfZael** [comment]
> @nerfZael probably is something related to the constraints defined in wrappers.io regarding package validation?

I think this is an issue with the express.js server settings on the persistence node gateway, I'll look into it

**Comment by dOrgJelli** [comment]
Can this be closed? NOTE: we've removed the "Polywrap metadata" feature, and instead are using the generic "resources" folder.

**Comment by dOrgJelli** [comment]
Update: still a potential problem, need to investigate express.js configuration.

**Comment by nerfZael** [comment]
Tested and it appears to be resolved. Closing...
