### ISSUE TITLE
Wrappers can be embedded into applications

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1077]
moved here from https://github.com/polywrap/documentation/issues/111

**Comment by dOrgJelli** [comment]
@nerfZael I think this can now be done, no?
https://github.com/polywrap/toolchain/blob/b57b1393d1aa5f82f39741d297040f84bf799ff1/packages/js/wasm/src/__tests__/in-memory-packages.spec.ts#L20-L28

I think we should:
- create tests showing this can be done w/ the client config & the config builder
- create documentation showing how to do this

**Comment by nerfZael** [comment]
Closed by #1445
