### ISSUE TITLE
I want to embed wrappers

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#1104]
We need a way to support embedding wasm wrapper within the host app.
Feature has been outlined here: https://hackmd.io/oTuN7E68R5O517KKDNv-KQ
Blocked by: 
- [x] #1102
- [x] #1103

**Comment by dOrgJelli** [comment]
Hey @nerfZael what is the spec for this now that the blocking issues are completed?

**Comment by nerfZael** [comment]
Now that the Plugin Refactor has been merged, it is done :)
