### ISSUE TITLE
I want use wrappers in Rust

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1105]
# Motivation
I want to be able to build Polywrap enabled apps in Rust. This requires the creation of a Polywrap Client in Rust.

# Prior Work
We already have 1 client in TypeScript that's in production:
https://github.com/polywrap/monorepo/tree/origin/packages/js/client

And 1 client in Python that's under development:
https://github.com/polywrap/python-client/

Additionally we've done some initial work on porting parts of the client to Rust here, but it is VERY outdated so we should probably start fresh:
https://github.com/polywrap/monorepo/tree/feat/rust-package/packages/rs

# Sub-Tasks
- [x] #1106
- [x] #1107
- [x] #1108
- [x] #1109
- [x] #1110

**Comment by cbrzn** [comment]
repository where rust client lives: https://github.com/polywrap/rust-client/
