### ISSUE TITLE
I want to develop WASM wrappers with real-time type safety

### ISSUE THREAD

**Issue by pileks** [Web3-API/prototype#1121]
Currently, while developing WASM wrappers, the only way to know whether we are writing the wrapper properly is to attempt a build of the wrapper. Working with large wrappers is exceptionally difficult for this reason.

- [x] #1458
  - Essentially, instead of directly exporting functions, they would export a class that extends the Module class found in `./wrap`
- [x] #1463
- [x] #1459
  - Runs codegen every time the schema definition changes

**Comment by dOrgJelli** [comment]
Update: PRs are live for the `IModule` changes.
