### ISSUE TITLE
uts46, sha3, and subgraph plugins are no longer in default plugins

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1125]
Parent story: https://github.com/polywrap/monorepo/issues/1124

The uts46, sha3, and subgraph plugins can be replaced with Rust wrappers. Each of these plugins can be removed from default plugins once it has a working wrapper.

- [ ] uts46 plugin is no longer in the default plugins
- [ ] sha3 plugin is no longer in the default plugins
- [ ] subgraph plugin is no longer in the default plugins

Depends on:

- https://github.com/polywrap/integrations/issues/102
- https://github.com/polywrap/integrations/issues/103
- https://github.com/polywrap/integrations/issues/104

**Comment by cbrzn** [comment]
hey @krisbitney would it make sense to remove the blocked status from here?

**Comment by krisbitney** [comment]
> hey @krisbitney would it make sense to remove the blocked status from here?

Yeah, it can be changed
