### ISSUE TITLE
I want use wrappers in Go

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1128]
# Motivation
I want to be able to build Polywrap enabled apps in Go. This requires the creation of a Polywrap Client in Go.

# Requested By
* https://www.notion.so/polywrap/Pocket-999a8232a1c04987a621ab8dddffe1e2

**Comment by cbrzn** [comment]
since we're currently mostly focusing in ethereum & client development (swift in particular), I don't have the time to execute this in the next month. looking for some one that can lead this

**Comment by dOrgJelli** [comment]
This has been released: https://github.com/polywrap/cli/releases/tag/0.11.0
