### ISSUE TITLE
I want use wrappers in Python

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1129]
# Motivation
I want to be able to build Polywrap-enabled apps in Python. This requires the creation of a Polywrap Client in Python.

# Progress
Here's the current WIP branches:
https://github.com/polywrap/toolchain/pull/1232

# Sub tasks
- [x] #1249
- [x] #1250
- [x] #1251
- [x] #1252
- [x] #1253
- [x] #1254
- [x] #1255

# Requested By
* https://www.notion.so/polywrap/Pocket-999a8232a1c04987a621ab8dddffe1e2

**Comment by rihp** [comment]
so to recap the quick sync we had today around the python client progress:

subinvokations are nearly working.

next steps would be working on:

- [ ] manifests
- [ ] Interfaces
- [ ] client config builder
- [ ] further testing wrappers
- [ ] Plugins
- [ ] uri resolution update
- [ ] finish readme

**Comment by rihp** [comment]
@Niraj-Kamdar has created a new repo for the python client 

https://github.com/polywrap/python-client

Details of the status of the implementation can be found in https://github.com/polywrap/python-client/issues/2

**Comment by Niraj-Kamdar** [comment]
Closing this since moved to the python-client repo
