### ISSUE TITLE
Remove default configuration from client

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1176]
**Is your feature request related to a problem? Please describe.**
This will reduce the memory footprint of the client.

**Describe the solution you'd like**
I'd like to be able to load a pre-packaged config, but it should be optional. I'd like plugins to be replaced with wrappers where possible.

**Additional context**
Depends on https://github.com/polywrap/monorepo/issues/1122

**Comment by dOrgJelli** [comment]
Some thoughts on the implementation here:
https://github.com/polywrap/toolchain/pull/1045#issuecomment-1225085814

**Comment by dOrgJelli** [comment]
This has been completed as part of the ClientConfigBuilder work.
