### ISSUE TITLE
fix logic for msgpack-js in case of nested map 

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#1193]
Currently nested msgpack deserializes as follows: 
```
    ExtData {
      type: 1,
      data: Uint8Array(11) [
        129, 163, 117, 115, 100,
        165,  50,  48,  50,  52,
         53
      ]
    }
```

Which is inaccurate, have a better way to deserializes the value of the map in msgpack-js

**Comment by krisbitney** [comment]
Resolved by https://github.com/polywrap/toolchain/pull/1194
