### ISSUE TITLE
Multi-Client Test Harness

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1202]
**Is your feature request related to a problem? Please describe.**
Currently we do not have a clean way of testing multiple clients, and forming a feature matrix. With the Python client being wrapped up in the near future, it would be nice to have a system created for this.

**Describe the solution you'd like**
Still TBD

**Additional context**
Some initial work has been done here: https://github.com/polywrap/technical-council/issues/2

**Comment by pileks** [comment]
Removed from `origin-qa` since other clients (Rust, Python) aren't part of `origin-qa`

**Comment by dOrgJelli** [comment]
This is currently being done here: https://github.com/polywrap/client-readiness
