### ISSUE TITLE
Reproducible build pipeline

### ISSUE THREAD

**Issue by benefacto** [Web3-API/prototype#121]
Split from #95 

**Goals:**
- Easily & consistently build web3api projects from their source files, enabling source verification

**Build Changes:**
- [x] Identify where & how code is currently built
The Web3API project is built and deployed via the Web3API CLI to hardcoded, locally running instances of [IPFS](https://github.com/Web3-API/prototype/blob/034b8c2decb646e677d252da5c273f18934e016d/packages/client-test-env/.env#L1) and [the Graph](https://github.com/Web3-API/prototype/blob/579d2dc860d1eb269da09487de68ef8267ef2144/packages/client-test-env/docker-compose.yml#L26) that were previously setup as the test environment: `npx w3 build \
--ipfs http://localhost:5001 \
--graph simplestorage,http://localhost:8020 \
--test-ens simplestorage.eth`
- [x] Build in consistent, isolated environment: [example of how to do this for a Python environment](https://pythonspeed.com/articles/reproducible-docker-builds-python/)
- [x] Add build configuration to file
- [x] Snapshot build environment (e,g, [`docker commit`](https://docs.docker.com/engine/reference/commandline/commit/)) before compiling to ensure reproducibility
- [x] Verify build is reproducible in a container snapshot

**Comment by dOrgJelli** [comment]
Here's a diagram to explain how I'm imagining this going:
![Deterministic-Builds](https://user-images.githubusercontent.com/5522128/106222129-e6d63800-61ac-11eb-8f91-453eafe6b06c.png)

Also here's the draw.io file: 
[Deterministic-Builds.txt](https://github.com/Web3-API/prototype/files/5891132/Deterministic-Builds.txt)

@namesty brought up a great point that there will be non-deterministic aspects of the build-env that we'll have to make deterministic. Some examples of this are:
- System Clock
- External Network Requests

I've done a little searching, and it looks like it'll be very difficult to mitigate these, and other unforeseen non-deterministic operations. I think that we can "deal with this when it's a problem", and only verify that the web3api build files (WASM, schema, manifest) are the same as what's published.
