### ISSUE TITLE
Bug: polywrap.test.yaml validation script URI is resolved relative to user cwd instead of manifest directory

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1228]
**Describe the bug**
It is possible to provide a path to a validation script in the `polywrap.test.yaml` manifest. But the path is resolved relative to the current working directory of the user. This is unexpected behavior.

**Expected behavior**
Let's say I put the manifest and validator files together in a subfolder called `workflows`. The files are then located at `workflows/polywrap.test.yaml` and `workflows/validator.cue`.

Then I add the following line to the manifest:
```yaml
validation: "./validator.cue"
```

Next I add a script to my package.json:
```json
"workflow":  "npx polywrap run -m ./workflows/polywrap.test.yaml"
```

I expect to be able to run the script from the root of my project. I will instead get an error saying the validator file cannot be found. The `run` command will look for the validator script in the project root instead of in the `workflows` folder.

**Comment by fetsorn** [comment]
@krisbitney Thank you for catching this!

**Comment by krisbitney** [comment]
fixed by https://github.com/polywrap/toolchain/pull/1229
