### ISSUE TITLE
Add WASM code coverage reporting to test running

### ISSUE THREAD

**Issue by benefacto** [Web3-API/prototype#123]
Split from #95 
Add code coverage, something like: `w3 test-recipes --coverage`

- find a tool that allows you to instrument WASM files for code coverage at run-time
- run the queries, extracting code-coverage data for each query
- aggregate all the separate runs into a single result, since each query starts up a new VM instance (may not matter)

There is no "general WASM code-coverage tool". People have adapted language specific code coverage tools to work with the WASM build target, like for example the C compiler LLVM's code coverage tooling. But there doesn't exist a WASM (language agnostic) code coverage tool.

**Comment by dOrgJelli** [comment]
Closing this as it is not currently possible to do generic wasm codecov.

**Comment by bbarwik** [comment]
Hey @benefacto @dOrgJelli , I've found a way to generate code coverage report for WASM files, maybe it will be useful to you - https://github.com/hknio/code-coverage-for-webassembly
