### ISSUE TITLE
Interfaces do not build without a Module

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1233]
**Describe the bug**
An interface cannot build without a module. It can be desirable to define an interface  so that multiple wrappers can share type definitions.

**Expected behavior**
Users may expect an interface to build without a module so that types can be imported from it.

**Additional context**
CIDT create an interface wrapper for the Near project and it does not build because there is no `Module` in the interface: https://github.com/polywrap/integrations/tree/near/borsh-wrapper/protocol/near/near-interface

**Comment by pileks** [comment]
It seems that this issue stems from the fact that their project's `type` is `wasm/interface` instead of `interface`.

Once this is fixed, it builds normally.

**Comment by krisbitney** [comment]
> It seems that this issue stems from the fact that their project's `type` is `wasm/interface` instead of `interface`.
> 
> Once this is fixed, it builds normally.

Oh wow, nice! That's fantastic. Thanks for resolving this.

**Comment by krisbitney** [comment]
Resolved by @pileks
