### ISSUE TITLE
Add support in web3api.env.yaml for hidden Docker modules

### ISSUE THREAD

**Issue by benefacto** [Web3-API/prototype#124]
Split from #95 , see 3 in [diagram](https://github.com/Web3-API/monorepo/issues/95#issuecomment-772089653) 

- ~~We could make it easier for Web3API devs by abstracting it more so they don't have to worry about understanding docker-compose. One potential way we could do this is by allowing them to install (via the w3 CLI) test environments. For example: `w3 test-env install @web3api/ipfs-test-env`. `@web3api/ipfs-test-env` could just be an NPM package that w3 could pull down and store locally. These test env packages would just contain simple docker-compose files. This way all a user would have to do there after is `w3 test-env up @web3api/ipfs-test-env @web3api/eth-test-env @web3api/ens-test-env`~~
- ~~Another way to abstract it which may be easier is to have (inside of the CLI) default supported environments in a "monolithic" docker-compose file. Imagine a single docker-compose file that's ready to go with ipfs, eth, arweave, cosmos, polkadot, etc etc. Then the user via the CLI could just specify the name of the services they want to stand up: `w3 test-env up ethereum ipfs graph-node`.~~
- ~~Adding ability to configure the CLI command via a config file, instead of passing in a ton of arguments. This file could be the web3api.test-env.yaml or web3api.env.yaml. This config file would map 1:1 with the available CLI arguments, so you could configure via CLI arguments, or through a config file. This is very useful for collaboration & versioning sake.~~

**Comment by dOrgJelli** [comment]
Closing for now, will create another issue to represent this nice-to-have feature in the future.
