### ISSUE TITLE
Move React package into integrations

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#1257]
Currently, the @polywrap/react-js package is in the toolchain repo.
Since this is an integration it should be moved to the integrations repo.

**Comment by dOrgJelli** [comment]
Agreed, we can create a new folder within integrations called `framework` that can include tailored framework integrations. Some others that would be cool to see here:
- Unity
- React-Native
- Django
- etc

**Comment by nerfZael** [comment]
> Agreed, we can create a new folder within integrations called `framework` that can include tailored framework integrations. Some others that would be cool to see here:
> 
> * Unity
> * React-Native
> * Django
> * etc

I like that!

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli isn't this completed?

**Comment by dOrgJelli** [comment]
Yes, we've moved the package here: https://github.com/polywrap/react
