### ISSUE TITLE
PackageToWrapperCacheResolver - Cache redirects

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#1258]
Currently, PackageToWrapperCacheResolver caches wrappers and turns packages into wrappers and caches them.
We should expand that to include caching redirects (URI to URI), so that the final resolution path stays the same regardless of whether or not the wrapper was fetched from cache

**Comment by dOrgJelli** [comment]
Great point, agreed! The URI resolution path should not change just because it was found in cache.
