### ISSUE TITLE
We shouldn't allow union of string and Uri everywhere and only expect Uri type

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#1265]
**Describe the bug**
Currently, we use the generic type `TUri extends Uri | string` everywhere which is basically a union of both Uri and string and since we do this at every level, we require sanitizing string to Uri for all the functions/methods. this isn't optimal and should be avoided. I don't see any issue in a user passing a new Uri object instead of a string, if a user really wants to pass the string and we want to allow this it should be done on the client side once and for all.

**Comment by krisbitney** [comment]
I'm not sure this is a good idea. I think this would make our libraries cleaner and more elegant for sure, but we would be doing so at the expense of the user experience.

**Comment by dOrgJelli** [comment]
IMO all user-facing functions (on the client) should support both, but everything underneath should use URI.

**Comment by Niraj-Kamdar** [comment]
Sorry for not explaining clearly. I only meant this for core and internal libs. User-facing lib like client-config can still support Union type if they want.

**Comment by krisbitney** [comment]
> Sorry for not explaining clearly. I only meant this for core and internal libs. User-facing lib like client-config can still support Union type if they want.

Yeah, okay, this makes sense. I had misunderstood before. Sounds good!
