### ISSUE TITLE
Create Uniswap Web3API

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#128]
Here's a first draft of the `schema.graphql`, created by going through the [SDK reference](https://uniswap.org/docs/v2/SDK/getting-started) and [guide](https://uniswap.org/docs/v2/javascript-SDK/quick-start/):
```graphql
enum ChainId {
  MAINNET
  ROPSTEN
  RINKEBY
  GORLI
  KOVAN
}

enum TradeType {
  EXACT_INPUT
  EXACT_OUTPUT
}

enum Rounding {
  ROUND_DOWN
  ROUND_HALF_UP
  ROUND_UP
}

type Token {
  chainId: ChainId!
  address: String!
  decimals: UInt8!
  symbol: String
  name: String
}

type TokenAmount {
  token: Token!
  amount: UInt256!
}

type Pair {
  token0: Token!
  token1: Token!
}

type Route {
  pairs: [Pair!]!
  input: Token!
}

type Trade {
  route: Route!
  amount: TokenAmount!
  tradeType: TradeType!
}

type Query {

  # Token
  tokenEquals(
    token: Token!
    other: Token!
  ): Boolean!

  tokenSortsBefore(
    token: Token!
    other: Token!
  ): Boolean!

  # Pair
  pairAddress(
    pair: Pair!
  ): String!

  pairLiquidityToken(
    pair: Pair!
  ): Token!

  pairReserve0(
    pair: Pair!
  ): UInt256!

  pairReserve1(
    pair: Pair!
  ): UInt256!

  pairOutputAmount(
    pair: Pair!
    inputAmount: TokenAmount!
  ): TokenAmount!

  pairInputAmount(
    pair: Pair!
    outputAmount: TokenAmount!
  ): TokenAmount!

  pairLiquidityValue(
    pair: Pair!
    token: Token!
    totalSupply: TokenAmount!
    liquidity: TokenAmount!
  ): TokenAmount!

  # Route
  routePath(
    route: Route!
  ): [Token!]!

  routeOutput(
    route: Route!
  ): Token!

  routeMidPrice(
    route: Route!
  ): TokenAmount!

  # Trade
  tradeExecutionPrice(
    trade: Trade!
  ): TokenAmount!

  tradeNextMidPrice(
    trade: Trade!
  ): TokenAmount!

  tradeSlippage(
    trade: Trade!
  ): TokenAmount!

  tradeMinimumAmountOut(
    trade: Trade!
    slippageTolerance: Float32!
  ): TokenAmount!

  tradeMinimumAmountIn(
    trade: Trade!
    slippageTolerance: Float32!
  ): TokenAmount!

  bestTradeExactIn(
    pairs: [Pair!]!
    amountIn: TokenAmount!
    tokenOut: Token!
    options: BestTradeOptions!
  ): [Trade!]!

  bestTradeExactOut(
    pairs: [Pair!]!
    tokenIn: Token!
    amountOut: TokenAmount!
    options: BestTradeOptions!
  ): [Trade!]!

  # Fetch
  fetchTokenData(
    chainId: ChainId,
    address: String!
    symbol: String
    name: String
  ): Token!

  fetchPairData(
    tokenA: Token!
    tokenB: Token!
  ): Pair!

  # Constants
  factoryAddress: String!
  initCodeHash: String!
  minimumLiquidity: UInt
}

type Mutation {
  swap(
    tokenIn: Token!
    tokenOut: Token!
    amountIn: UInt256!
  ): Ethereum_Receipt!

  exec(
    trade: Trade!
  ): Ethereum_Receipt!
}
```

Estimated implementation times:
JS Web3API plugin - 5 hours
WASM Web3API - 140 hours

NOTE: The Web3API tool-chain is in pre-alpha, and very few "real world" WASM Web3APIs have been created thus far. Modifications to the backing tool-chain may be required, which will created delays in the estimated times above.

**Comment by dOrgJelli** [comment]
The proposal has been posted to Uniswap Grants, awaiting feedback. Thank you @rihp for pushing this along!

**Comment by dOrgJelli** [comment]
```typescript
const client = new Web3ApiClient()

client.query({
  uri: "ens/api.uniswap.web3api.eth",
  query: `mutation {
    swap(
      from: "ETH",
      to: "0x...",
      ....
  }`
})
```

**Comment by morrigan** [comment]
Few things here to note:

* The constants part would be great to solve when we have #140. For now, we can always pass it as arguments.
* Is any plugin work required for this? Seems like we can use only the existing Ethereum plugin as-is.

@krisbitney do you want to take the query methods and we can take the mutations? Mutations depend on some of the query methods so would be good to take that first. You can sync with @mpetrun5 and @MakMuftic on Discord or call regarding any implementation details :)

**Comment by krisbitney** [comment]
> Few things here to note:
> 
> * The constants part would be great to solve when we have #140. For now, we can always pass it as arguments.
> * Is any plugin work required for this? Seems like we can use only the existing Ethereum plugin as-is.
> 
> @krisbitney do you want to take the query methods and we can take the mutations? Mutations depend on some of the query methods so would be good to take that first. You can sync with @mpetrun5 and @MakMuftic on Discord or call regarding any implementation details :)

Yes, that works for me. I'll get started today!
