### ISSUE TITLE
Ignore unused code warnings in rust bindings

### ISSUE THREAD

**Issue by fetsorn** [Web3-API/prototype#1293]
**Is your feature request related to a problem? Please describe.**
rust bindings always have dead code and used variables, which throws unnecessary warnings during build.

**Describe the solution you'd like**
Add `#![allow(dead_code, unused_variable)]` to the top of every binding template.

**Comment by MarcGuiselin** [comment]
Not necessary to add to the top of all templates.

`#![allow(unused)]` applies to descendent modules as well and should be a better catch-all.

Just needs to be added to the top of `wrap/mod.rs`
