### ISSUE TITLE
Add docker (compose) file(s) for spinning up ENS

### ISSUE THREAD

**Issue by benefacto** [Web3-API/prototype#130]
Add support for [ENS](https://ens.domains)

**Comment by dOrgJelli** [comment]
No need to focus on Cosmos & Arweave right now, since we're focusing solely on ETH + ENS & IPFS right now. We can add other networks later on down the road (in a month or so).

**Comment by benefacto** [comment]
> 
> 
> No need to focus on Cosmos & Arweave right now, since we're focusing solely on ETH + ENS & IPFS right now. We can add other networks later on down the road (in a month or so).

Got it. I split that out into #131

**Comment by dOrgJelli** [comment]
Moving this to: https://github.com/Web3-API/monorepo/issues/209
