### ISSUE TITLE
Codegen outputs `[outputDir]/src/wrap` instead of requested output dir

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1312]
**Describe the bug**
Using the following command:
```bash
npx polywrap codegen -m ./src/__tests__/types/polywrap.app.yaml -g ./src/__tests__/types/wrap
```
The output wrap folder is located at:
`./src/__tests__/types/src/wrap`

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
TODO

**Expected behavior**
I expect output at `./src/__tests__/types/wrap`

**Relevant environment details:**
- OS: MacOS

**Comment by dOrgJelli** [comment]
This is fixed here: https://github.com/polywrap/toolchain/pull/1318
