### ISSUE TITLE
A copy of tests is run from .polywrap

### ISSUE THREAD

**Issue by fetsorn** [Web3-API/prototype#1314]
**Describe the bug**
After the build strategy update tests are now copied to .polywrap during build, and jest picks them up.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
On 0.9.0 version, go into a rust wrapper project with tests, build and run jest.

**Expected behavior**
Only tests in src/ are picked up by jest

**Relevant environment details:**
- Linux x64

**Comment by dOrgJelli** [comment]
This is fix here: https://github.com/polywrap/toolchain/pull/1318
