### ISSUE TITLE
CLI: Run (Test) Command Exits W/O Error When Wrapper Not Found

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1358]
**Describe the bug**
When a `polywrap run` loads a `polywrap.test.yaml` manifest that includes a wrapper URI that is not resolvable (doesn't exist), the command seems to exit prematurely w/o any error message.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Clone the toolchain repo
- Build packages (so CLI is present)
- `cd ./packages/test-cases/cases/cli/run/001-yaml-workflow/`
- make sure `./packages/test-cases/cases/cli/run/run-test-wrapper/build` doesn't exist
- run `../../../../../cli/bin/polywrap run`
- The command exits w/o any error:
```
001-yaml-workflow % ../../../../../cli/bin/polywrap run
🔄 Manifest loaded from ./polywrap.test.yaml
✅ Manifest loaded from ./polywrap.test.yaml
```

If you now go and build the `run-test-wrapper` wrapper, the run command will succeed.

**Expected behavior**
There should be an error stating that the wrapper cannot be found.

**Relevant environment details:**
- CLI Version: `0.9.3`

**Comment by krisbitney** [comment]
I tried to reproduce the error on the `origin-dev` branch and I got this output. What do you think?

<img width="1440" alt="Screen Shot 2022-10-28 at 2 24 08 PM" src="https://user-images.githubusercontent.com/39842820/198553571-723c0276-6468-4282-b27c-551fc2b7be4d.png">

<img width="1440" alt="Screen Shot 2022-10-28 at 2 27 11 PM" src="https://user-images.githubusercontent.com/39842820/198554161-48bf6764-a3cc-422e-a242-1088c870bd0f.png">

**Comment by dOrgJelli** [comment]
@krisbitney does this result in an exit code of non-zero?

**Comment by krisbitney** [comment]
> * ../../../../../cli/bin/polywrap run

I looked into it and it doesn't, no.

Each step of each job is a distinct invocation. Some can fail while others succeed. So it makes sense that it works this way.

**Comment by krisbitney** [comment]
> @krisbitney does this result in an exit code of non-zero?

I looked into it and it doesn't, no.

Each step of each job is a distinct invocation. Some can fail while others succeed. So it makes sense that it works this way.
