### ISSUE TITLE
"Unsupported type" error on `codegen` when custom type in Map

### ISSUE THREAD

**Issue by sraver** [Web3-API/prototype#1371]
**Describe the bug**
"Unsupported type" error raises on the type generation when using custom types on a Map on the `schema.graphql`.
It also happens on the generation of types when importing an interface with custom types on a Map.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Define an interface like:
```
type Module {
    getMetadata: Metadata!
}

type Metadata {
    tokens: Map! @annotate(type: "Map<String!, [Token!]!>!")
}

type Token {
    address: String!
}
```
2. Build and deploy the interface
3. Import the interface into a module as usual, and implement `type Module implements Interface_Module {}`
4. Generate types `yarn codegen`

**Expected behavior**
Process should complete as usual and the types should be created inside `src/wrap`

**Screenshots / logs**
```
...
✅ Manifest loaded from ./src/__tests__/types/polywrap.app.yaml
🔄 Generate types
❌ Failed to generate types: Error: Unsupported type Token
Error: Unsupported type Token
```

**Relevant environment details:**
- Debian 11
- Polywrap 0.9.3

**Additional context**
The error doesn't happen when instead of a custom type, a primitive one is used, like String.

**Comment by Niraj-Kamdar** [comment]
Some updates on the issue. In our schema-compose package, we aren't adding the namespace to the map types which causes the codegen to fail.
