### ISSUE TITLE
Add Linting For GraphQL & JSON files

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#142]
Currently the linter does not run for GraphQL and JSON files, leading to inconsistencies making their way into the codebase.

**Comment by morrigan** [comment]
In plugins? and tests?

**Comment by dOrgJelli** [comment]
I think I remember creating this issue after seeing some formatting differences in GraphQL files. For JSON we'd simply want to make sure it's valid JSON.

Here are two example files that it would be nice to have linting for:
* https://github.com/Web3-API/monorepo/blob/prealpha/packages/js/plugins/ethereum/schema.graphql
* https://github.com/Web3-API/monorepo/blob/prealpha/packages/manifest-schema/formats/0.0.1-prealpha.1.json

The hope is that this helps keep our GraphQL looking similar across all packages (and valid), and JSON files valid.
