### ISSUE TITLE
Wasm-as wrapper developers extend & implement IModule interface from wrap codegen

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#1458]
Currently, we have the module type in our GraphQL schema which contains functions that wrapper devs would implement but unlike plugin where plugin devs can easily extend the generated `IModule` interface, In the case of the wrapper, wrap dev needs to define the global functions with appropriate args, and return type. It would be more developer-friendly if we also provide an interface that developers can extend and provide an implementation for.

Let's take an example of a simple wrapper with the following schema:
```graphql
type Module {
  simpleMethod(arg: String!): String!
}
```
**Now let's see how the codegen and wrap devx. would look like for Assemblyscript dev.**
Here's how generated IModule interface would look for the simple wrapper with above schema
```typescript
export abstract class IModule {
  abstract simpleMethod(
    args: Types.Args_simpleMethod
  ): string;
}
```

Here's how a wrap dev can implement the `Module` class by simply extending it
```typescript
export class Module extends IModule {
  simpleMethod(args: Args_simpleMethod): string {
    return args.arg;
  }
}
```
For method that needs to use env, `env` can be accessed with `this.env` readonly property.

**Comment by dOrgJelli** [comment]
Can we make this issue a bit more descriptive? I think a better title might be "Wasm Wrapper Developers Extend & Implement Base Module Class From Codegen". Also having a description with a clear code snippet of what exactly this means would be helpful.
