### ISSUE TITLE
Implement a polywrap codegen --watch  CLI command

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#1459]

**Comment by pileks** [comment]
@Niraj-Kamdar Would this simply entail running codegen when a watcher detects file changes, similar to `build --watch`?

**Comment by Niraj-Kamdar** [comment]
@pileks Yes I think so

**Comment by pileks** [comment]
@Niraj-Kamdar thanks for clarifying - it seems like a relatively straightforward update.
I can take this one as soon as #1385 is merged!
