### ISSUE TITLE
constant that maps all URIs in default config bundle

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1466]
**Is your feature request related to a problem? Please describe.**
Let's say I want to invoke the filesystem plugin directly and I'm using the default config bundle. I need to know the filesystem plugin's URI to do it. 

How do I learn the URI? I read it in the client config builder code.

And what if the URI changes? I need to change my code.

This is not a user-friendly solution for our users!

**Describe the solution you'd like**
In the default config bundle, we have a couple of constants:
```typescript
export const defaultIpfsProviders = [
  "https://ipfs.wrappers.io",
  "https://ipfs.io",
];

export const defaultWrappers = {
  sha3: "wrap://ens/goerli/sha3.wrappers.eth",
  uts46: "wrap://ens/goerli/uts46-lite.wrappers.eth",
  graphNode: "wrap://ens/goerli/graph-node.wrappers.eth",
  concurrentInterface: "wrap://ens/goerli/interface.concurrent.wrappers.eth",
};
```

These are super useful. I think we should have one or more constants that contain ALL of the default URIs used in the default config bundle.

```typescript
export const defaultWrappers = {
  ...
  filesystem: "wrap://ens/fs.polywrap.eth",
  http: "wrap://ens/http.polywrap.eth",
  logger: "wrap://plugin/logger",
  ...
};
```

Now if I wanted to directly invoke the filesystem plugin, I could easily reference the URI using `defaultWrappers.filesystem`.

**Describe alternatives you've considered**
TODO

**Additional context**
N/A

**Comment by dOrgJelli** [comment]
I'm onboard with this! I think this should be exported from the default config "bundle" inside of the config builder.
