### ISSUE TITLE
buildx docker container still running after build

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#1479]
**Describe the bug**
The docker container with a name like `buildx_buildkit_polywrap-build-env-804329be-892e-4979-bdc7-627685ee8fb20` remains running after building a wrapper. It is not automatically stopped.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
I think it can be replicated by building any wrapper with the test env's `buildWrapper` function.

**Expected behavior**
I would expect the container to be stopped when the build comletes.

**Screenshots / logs**
<img width="818" alt="Screenshot 2023-01-11 at 3 28 32 PM" src="https://user-images.githubusercontent.com/39842820/211776189-f2a88dd8-bf66-424e-a359-b2a731e96a69.png">

**Relevant environment details:**
- Mac OS with Apple cpu

**Comment by dOrgJelli** [comment]
@Niraj-Kamdar do you have thoughts on this? I remember you had worked on the docker buildx integration a while back.

**Comment by Niraj-Kamdar** [comment]
From what I researched, that's how buildkit works. It basically spawn a new container in which the docker image gets created. It will reuse the same container for building the same image more efficiently.

But there is an option to remove image and builder container if you want to in the build manifest. I wouldn't recommend it unless you are in a constrained environment. You can just regularly `docker system prune`

**Comment by Niraj-Kamdar** [comment]
Alternatively, you can turn on cache and set remove image and builder to true, it won't have most optimal performance but can still be faster than building image from scratch.

**Comment by dOrgJelli** [comment]
Hey @krisbitney @Niraj-Kamdar, after doing a bit of a deep dive into `docker buildx ...` recently, I realized that we should indeed be removing the "builder instance" we create.

Effectively what we want to be doing (in the CLI's build strategy) is the following:
```
docker buildx create --use --name foo-wrapper-builder
docker buildx ...
docker buildx rm foo-wrapper-builder
```

https://docs.docker.com/engine/reference/commandline/buildx_create/
https://docs.docker.com/engine/reference/commandline/buildx_rm/

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli We already have an option to do so in build manifest, do you mean we should do this by default?

**Comment by dOrgJelli** [comment]
Yah I think we should do this by default.

**Comment by krisbitney** [comment]
I also think it should be removed by default. I think it's a bad practice to leave a docker container running on the user's machine by default, even if the container is useful. It should be opt-in.
