### ISSUE TITLE
Detect Infinitely Recursive Object Relationships

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#149]
Create schema sanitization logic that detects infinitely recursive object relationships, for example:
```graphql
type InfiniteRoot {
  prop: InfiniteProp!
}

type InfiniteProp {
  root: InfiniteRoot!
}
```

Currently if you do this, and include `InifiniteRoot` as an argument on a method (for example), the generated deserialization code is able to detect this, since it's impossible to ever fully satisfy the construction. For example:
```graphql
type Query {
  method4(
    arg: InfiniteRoot!
  ): Result!
}
```
given the schema above, and the query...
```graphql
query {
  method4(
    arg: {
      prop: {
        root: {
          prop: {

          }
        }
      }
    }
  )
}
```
the generated WASM deserialization code will throw the following error:
```
WasmWeb3Api: Thread aborted execution.
Message: __w3_abort: Missing required property: 'root: InfiniteRoot'
```

So without this schema sanitization code, developers are able to create these bad relationships, which can lead to them exposing query functions that can never be invoked properly.

**Comment by namesty** [comment]
Hey @dOrgJelli can I take this one?

**Comment by dOrgJelli** [comment]
Yep! I'll assign to you
