### ISSUE TITLE
Network Specific ENS Lookups

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#159]
Currently, the ENS api-resolver looks for packages on the default network the ethereum web3pai is currently using. This becomes a problem when an API is published on another network's ENS registry, and you'd like to use it for transactions on another network.

I propose that we utilize the URI's path section to solve this problem. For example:
`w3://ens/rinkeby/api.domain.eth`

The ENS Web3API would then realize that the user is requesting a specific network, and resolve on that network. If there is no network provided, the default ethereum network will be used.

This will require updating the Ethereum Web3API interface, and allowing the caller of `callView` (among other functions) to provide custom configurations as to what network provider to use.

**Comment by morrigan** [comment]
Hey @krisbitney @dOrgJelli we proposed solving this one, @mpetrun5 might have messed up assignments, sorry about that one :) Currently waiting for #141 to finish. Ok?

**Comment by krisbitney** [comment]
My attempt to solve this is in branch network-specific-ens-lookup

**Comment by dOrgJelli** [comment]
Opened a PR for Kris' work in the plugins here: https://github.com/Web3-API/monorepo/pull/228

Would be great to form consensus on the approach he's taken (network option on the Ethereum schema) so that we can use it for the ENS WASM Web3API. Would like to get this merged soon :)
