### ISSUE TITLE
Build error with `@types/node/ts4.8/test.d.ts` when setting up test environment

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/prototype#1640]
## Description
When setting up the test environment for a new Polywrap project, I encountered build errors related to `@types/node/ts4.8/test.d.ts`. This issue occurs after running `yarn test:env:up`.

## Steps to reproduce
1. Create a new project using `npx polywrap create wasm assemblyscript <project-name>`
2. Run `nvm install && nvm use` and `yarn` to install dependencies
3. Execute `yarn build` to build the Polywrap wrapper
4. Run `yarn test:env:up` to set up the test environment

## Expected behavior
The test environment should be set up without any errors.

## Actual behavior
The following error messages appear:

```bash
 > [eth-ens-ipfs-ens 8/8] RUN yarn build:
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(706,21): error TS1005: ',' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,19): error TS1005: ',' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,27): error TS1005: ':' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,36): error TS1005: ',' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,55): error TS1005: '{' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,64): error TS1005: ',' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(711,77): error TS1005: ',' expected.
#19 2.274 node_modules/@types/node/ts4.8/test.d.ts(715,22): error TS1005: ',' expected.
#19 2.310 error Command failed with exit code 2.
#19 2.310 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1

failed to solve: executor failed running [/bin/sh -c yarn build]: exit code: 1
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
```

## Additional information
Device: Macbook M2
Docker Desktop version: v4.17.0

**Comment by cbrzn** [comment]
hey this should be fixed - which version of the toolchain are you using? @kev-ngo

**Comment by kev-ngo** [comment]
@cbrzn I'm using:

    "polywrap": "0.9.6",
    "@polywrap/wasm-as": "0.9.6"
    
This is the default version when I run `npx polywrap create wasm assemblyscript <project-name>`

**Comment by pileks** [comment]
This has been resolved by https://github.com/polywrap/toolchain/pull/1635 for the currently released version of Polywrap, but the fix is not yet released. Will be a part of `0.9.7`.
We can close the issue once `0.9.7` is released.
