### ISSUE TITLE
CLI - `docs start` command

### ISSUE THREAD

**Issue by pileks** [Web3-API/prototype#1649]
The `docs start` command should start a local HTTP server with a version of `docs.wrappers.io` for the Wrap currently in development.

Changing/rebuilding the Wrap's source files should update the documentation website.

Note - maybe the best approach for this is for us to publish a Docker image with the latest Wrap Docs site and options to watch a folder/files for changes.

**Comment by dOrgJelli** [comment]
Closing this as it's not clear we need this feature.
