### ISSUE TITLE
Create Command - Projects should always use latest polywrap package versions

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1701]
**Describe the bug**
Currently the create commands generates projects that use an outdated version of polywrap's packages. This should automatically use the latest version available.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run `polywrap create ...`, and see that the project is using an older version of polywrap's packages.

**Expected behavior**
Use latest version.

**Comment by krisbitney** [comment]
I tried to reproduce this using `yarn polywrap create wasm rust testwrap` in the toolchain repo's `origin-dev` branch.

I think `polywrap create` does use the latest version of polywrap, `0.10.3`. Before the release of `0.10.x`, I know it was ignoring the "pre" versions and was treating `0.9.x` as the latest version. Do you think that explains the issue or did you get an older polywrap version after the release of `0.10.x`?
