### ISSUE TITLE
`polywrap.docs.yaml` Doesn't Work For Interfaces

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#1802]
**Describe the bug**
When building a wrap interface, the `polywrap.docs.yaml` manifest is ignored for the project.

**Please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Create an interface project
- Define a `polywrap.docs.yaml` manifest
- Link it in the `polywrap.yaml`'s `extensions.docs` property
- Run `polywrap build`
- Inspect the `build/` folder, the doc manifest is not emitted.

**Comment by pileks** [comment]
As stated when we were working on Wrapscan initially (and assuming we're still using Wrapscan as our source of truth for the docs manifest) only wraps (not interfaces) should be documented right now.
While accidental, we need to consider whether we do want to have docs emitted for interfaces. IMO the answer is **yes**, as I'm sure we'll soon want interfaces within Wrapscan too.
