### ISSUE TITLE
IPFS Deployer possibly duplicates subdirectory paths when deploying

### ISSUE THREAD

**Issue by pileks** [Web3-API/prototype#1846]
When deploying using the IPFS deployer, dirs within dirs possibly has an issue wherein subpaths are "multiplied":

Structure of build dir:
```
├── docs
│   ├── pages
│   │   └── readme.md
│   └── polywrap.docs.json
├── wrap.info
└── wrap.wasm
```

Structure of deployment to IPFS:
https://ipfs.io/ipfs/QmaG1butqzL7vXqs5hZCkba4LAiGStrh3vx6eKz8sdFfDo/
```
├── docs
|   |
|   └──docs
│      ├── pages
│      │   └── readme.md
│      └── polywrap.docs.json
├── wrap.info
└── wrap.wasm
```

Notice the difference in the docs dir - the path to the wrap readme is different:
docs/pages/readme.md - local build dir
vs
docs/docs/pages/readme.md - what's on IPFS

Further investigation warranted.

**Comment by dOrgJelli** [comment]
This should be fixed within `polywrap` CLI version `0.11.1`
