### ISSUE TITLE
Create Polkadot Web3API

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#195]
TODO

**Comment by mpetrunic** [comment]
I would be careful with that as it's not that simple. Substrate based chains have governance based updates which can break app. Especially considering there is handful of common rpc-apis that you are used to fetch metadata to dynamically build code to call rest of endpoints. Also polkadot node has http api but it's hard to do anything meaningful with it (all polkadot apps use ws).

**Comment by dOrgJelli** [comment]
Thanks so much for your insight @mpetrunic, I'm still investigating the requirements of this myself. Would you have time to meet sometime soon to discuss? If so please DM :pray:
