### ISSUE TITLE
Create READMEs For Each Package

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#205]
Create READMEs for each package that are ideally "self documenting", which will allow us to continue to develop the package and add features without having to constantly update the README. This is idealistic, but a goal to strive for.

**Comment by kev-ngo** [comment]
I'll prioritize this after the Uniswap Web3API docs.  

It will be inspired by Hardhat's plugins documentation: https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html

**Comment by kev-ngo** [comment]
Hey @dOrgJelli , For some of these READMEs, would I be able to copy and paste over what I have currently for the dev tools section of the docs (e.g. [@web3api/cli](https://docs.web3api.dev/devtools/web3api-cli))?

When you say self-documenting, are you referring to tools/libraries to automatically document these npm packages?

**Comment by dOrgJelli** [comment]
@nerfZael suggested creating READMEs at various levels of the folder structure, not just the package's root. This way separate parts of the codebase can have tailored descriptions that talk about them in more detail, and not just relying on comments.

**Comment by fetsorn** [comment]
These are READMEs that only contain "TODO" at the moment
- [ ] [packages/schema/bind/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/schema/bind/README.md)
- [ ] [packages/schema/compose/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/schema/compose/README.md)
- [ ] [packages/cli/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/cli/README.md)
- [ ] [packages/schema/parse/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/schema/parse/README.md)
- [ ] [packages/core-interfaces/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/core-interfaces/README.md)
- [ ] [packages/js/react/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/react/README.md)
- [ ] [packages/wasm/as/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/wasm/as/README.md)
- [ ] [packages/js/client/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/client/README.md)
- [ ] [packages/js/plugins/uts46/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/uts46/README.md)
- [ ] [packages/js/plugins/sha3/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/sha3/README.md)
- [ ] [packages/js/plugins/ipfs/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/ipfs/README.md)
- [ ] [packages/js/plugins/graph-node/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/graph-node/README.md)
- [ ] [packages/js/plugins/filesystem/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/filesystem/README.md)
- [ ] [packages/js/plugins/ethereum/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/ethereum/README.md)
- [ ] [packages/js/plugins/ens/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins/ens/README.md)
- [ ] [packages/js/core/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/js/core/README.md)
- [ ] [packages/test-cases/cases/cli/infra/local-packages/dev-server/README.md](https://github.com/polywrap/monorepo/tree/prealpha/packages/test-cases/cases/cli/infra/local-packages/dev-server/README.md)

**Comment by fetsorn** [comment]
These are READMEs that contain "TODO" at the moment
- [ ] [packages/schema/bind/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/schema/bind/README.md)
- [ ] [packages/schema/compose/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/schema/compose/README.md)
- [ ] [packages/cli/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/cli/README.md)
- [ ] [packages/schema/parse/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/schema/parse/README.md)
- [ ] [packages/core-interfaces/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/core-interfaces/README.md)
- [ ] [packages/js/react/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/react/README.md)
- [ ] [packages/wasm/as/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/wasm/as/README.md)
- [ ] [packages/js/client/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/client/README.md)
- [ ] [packages/js/plugins/uts46/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/uts46/README.md)
- [ ] [packages/js/plugins/sha3/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/sha3/README.md)
- [ ] [packages/js/plugins/ipfs/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/ipfs/README.md)
- [ ] [packages/js/plugins/graph-node/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/graph-node/README.md)
- [ ] [packages/js/plugins/filesystem/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/filesystem/README.md)
- [ ] [packages/js/plugins/ethereum/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/ethereum/README.md)
- [ ] [packages/js/plugins/ens/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/plugins/ens/README.md)
- [ ] [packages/js/core/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/js/core/README.md)
- [ ] [packages/test-cases/cases/cli/infra/local-packages/dev-server/README.md](https://github.com/polywrap/monorepo/tree/prealpha-dev/packages/test-cases/cases/cli/infra/local-packages/dev-server/README.md)
