### ISSUE TITLE
Simple-storage demo (setupClient.ts): ethereum.enable() deprecated per MetaMask docs

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/prototype#236]
## Issue
In the file `/demos/simple-storage/dapp/src/web3api/setupClient.ts`, the `ethereum.enable()` method is deprecated.

## Proposed fix
MetaMask docs advise using the following method instead:
`ethereum.request({ method: 'eth_requestAccounts' })`

## Source
[MetaMask docs](https://docs.metamask.io/guide/ethereum-provider.html#legacy-properties)

**Comment by dOrgJelli** [comment]
Fixed in the demos repo here: https://github.com/Web3-API/demos/commit/189ccec6671aba7430abfcd2a692f6bac3974c15
