### ISSUE TITLE
Register Custom Redirects When Using CLI

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#244]
Support `--redirects` flag where you provide a `js` file that returns custom redirects to be added to the client.

This will enable custom plugins to be used through the CLI.

Use this for all commands that instantiate a Web3API Client (`w3 query`, other?)

**Comment by krisbitney** [comment]
Unassigned myself after seeing this is being worked on: https://github.com/Web3-API/monorepo/pull/310

There are two other commands that use the client: Build and Codegen. Both use the client indirectly, through their use of SchemaComposer. Both commands already have options for a custom IPFS provider and/or custom ENS address. I think the SchemaComposer uses only the IPFS and ENS plugins. The changes to Build and Codegen could be essentially the same as the changes to Query (plus some straightforward changes to SchemaComposer), but with the added question of whether to remove the IPFS/ENS options or have them override --redirects (or vice versa).

You can use the test I wrote for this in branch cli-custom-redirects. It demonstrates using custom redirects to query an API hosted on IPFS without the test env up.
