### ISSUE TITLE
Enable Web3API CI Using `w3 query ./recipe.json`

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#247]
Enable the use of the `w3 query ...` command in CI by:
- Exiting the process with exitCode 1 upon an error being hit
- anything else needed?

This will allow us to run CI on the Web3APIs we have build so far (Console, IPFS, ENS, etc) under the ./packages/apis/ directory.

**Comment by cbrzn** [comment]
This has been solved with the Jobs PR
