### ISSUE TITLE
Use JSON For Manifest Build Artifacts

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#249]
Currently, manifests are authored using YAML, and then that same YAML is copied into the build folder. These manifest build artifacts (ex: `web3api.yaml`) are then downloaded by the Web3API client, parsed, and used at run-time.

@jeffscottward has suggested we use JSON for manifest build artifact for the following reasons:
- JSON is faster to parse (deserialization)
- JSON is easier to implement a parser for and has more implementations in various languages

Source: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1048.2508&rep=rep1&type=pdf

Source changes needed:
- [ ] CLI build command should output JSON versions of the manifest files (non-pretty versions to minimize size) to the build folder.
- [ ] Web3API Client should fetch `web3api.json` instead of `web3api.yaml`, and pase it as JSON.

**Comment by mpetrunic** [comment]
Just wanted to leave this, people usually prefer yaml for config/manifest since it allows comments 🙂

**Comment by dOrgJelli** [comment]
Agreed @mpetrunic. The idea is that developers will author their manifests using YAML, but the build pipeline will output them as JSON to the build folder, which will then be published to decentralized storage.

We will (in the future) have "verified source code" on the Web3Hub, so if someone wanted to surface the original manifest files they can using that feature.
