### ISSUE TITLE
Configure `open.web3api.eth` Subdomain

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#262]
In order to allow anyone to add their API to the open registry on ENS, we need to configure the `open.` subdomain accordingly. This should be done on Rinkeby first for testing, then on mainnet. This work is required by the Web3Hub team.

Some details...

In this article (https://medium.com/@eric.conner/the-ultimate-guide-to-ens-names-aa541586067a) they walk through doing just this, but it's pretty outdated and doesn't use the latest ENS addresses post-migration.

It appears the necessary subdomain registrar contracts are located here: https://github.com/ensdomains/subdomain-registrar

In the above repositories issues, you can find a few talking about incorrect addresses in the various blog posts talking about how to set this up. Some more digging is needed to find a proper way to setup this registrar to our subdomain.

**Comment by namesty** [comment]
Hey! As we spoke in our last sync, here's a recipe in pseudo to illustrate an easy way, with our ENS web3api, to:

1. Set up and configure the `open.web3api.eth` subdomain|
2. Register a new subdomain from that one

```ts
//PSEUDO-CODE Recipe to deploy and configure public subdomain
const ensAddress = "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
const publicResolverAddress = "0x..."
const label = "mysubdomain"
const owner = "0x..."
const domain = "public.domain.eth"

const fifsRegistrarAddress = await deployFIFSRegistrar(ensAddress, domain)
await setSubdomainOwner(domain, fifsRegistrarAddress, ensAddress)

//PSEUDO-CODE Recipe to register subdomain under public subdomain

await registerSubnodeOwnerWithFIFSRegistrar(label, owner, fifsRegistrarAddress)
await setResolver(`${label}.${domain}`, publicResolverAddress, ensAddress)
```

**Comment by dOrgJelli** [comment]
This has been completed on Rinkeby, and should be trivial w/ the scripts setup to do the same on mainnet. Going to close this now.
