### ISSUE TITLE
`w3 query ...` - Support Querying Non-Testnet APIs

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#291]
Currently, the `w3 query ...` command requires the test-env to be active. This is note needed when trying to query a mainnet Web3API (ex: `ens/helloworld.web3api.eth`).

**Comment by namesty** [comment]
Hey friends, can I take this one? @dOrgJelli

**Comment by dOrgJelli** [comment]
Sure thing @namesty !

**Comment by krisbitney** [comment]
This is resolved by PR #310 and Issue #244.
