### ISSUE TITLE
Support JSON as a Base Schema Type

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#302]
Within API schemas, we've found multiple use cases for using JSON as a base type. Currently `String` is used in its place, but this makes it a bit ambiguous to the user.

Ideally `JSON` could be a supported base type, and in the future this could be implemented using our extendable base-type standard hypothesized here:
https://github.com/Web3-API/monorepo/issues/103

**Comment by krisbitney** [comment]
This package looks helpful but possibly abandoned: https://github.com/near/assemblyscript-json
