### ISSUE TITLE
Demo Integration Tests

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#305]
Since the demos have been moved to [another repo](https://github.com/web3-api/demos), we do not have an automated way to ensure new releases of the tool-chain don't break them.

We should add automated build & test of all projects in the demos repo to the monorepo's CI workflow.

**Comment by Niraj-Kamdar** [comment]
I don't like the idea of having tests for integrations running in monorepo CI, It would be like React testing all the websites using React before releasing new version. We should have CI for that in integrations repo and test those there whenever we make new release for any of our integrations.

**Comment by dOrgJelli** [comment]
Yes I agree, this is a great point. This should instead live inside of the Demo repo's workflows.
