### ISSUE TITLE
FileSystem Web3API Resolver

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#307]
In order to facilitate loading Web3APIs from a local folder on the developer's file system, we can create a FileSystemPlugin which implements the api-resolver interface. This will allow us to fetch Web3APIs with the following URIs:
`w3://fs/some/directory`

This is very useful when developing a Web3API, and wanting to test it without deploying it to a local IPFS node + testnet ENS domain.

**Comment by krisbitney** [comment]
I think this is the same as Issue #490, which is resolved by PR #503.
