### ISSUE TITLE
Cannot Set EthereumPlugin's Network Key Using String

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#311]
The following code does not compile:
```typescript
const network = "rinkeby";

ethereumPlugin({
  networks: {
    `${network}`: {
      provider: ...
    }
  }
})
```

**Comment by krisbitney** [comment]
The solution to this is a nuance in JavaScript. String templates are expressions, and expressions cannot be property names. But we can make it work with the addition of an additional syntax element.

ECMA2015 introduced [computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names). To use string templates as property names, we just need to surround them in brackets and the client compiles as expected.

This is okay:
```
const stringTemplateNetwork = "stringTemplateNetwork";
expect({
  [`${stringTemplateNetwork}`]: {
    provider: ethereum,
  }
}).toStrictEqual({
  "stringTemplateNetwork": {
    provider: ethereum,
  }
})
```

And this console log:
```
console.log({
  [`${stringTemplateNetwork}`]: {
    provider: ethereum,
  }
});
```
Prints the following:
```
console.log
  { stringTemplateNetwork: { provider: 'http://localhost:8545' } }
```
