### ISSUE TITLE
Make as-bigint package prod ready

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#313]
- Setup CI/CD properly
- Contact AssemblyScript community about adding a link to this here: https://www.assemblyscript.org/built-with-assemblyscript.html
- Add documentation to the README

Package: https://github.com/Web3-API/as-bigint

**Comment by krisbitney** [comment]
I added documentation to the repo readme and created a pull request to get the as-bigint repo added to the assemblyscript page. The pull request can be viewed here: https://github.com/AssemblyScript/website/pull/72.

What all do I need to do for CI/CD? Right now I have it linting and running tests.

**Comment by dOrgJelli** [comment]
The repo looks fantastic @krisbitney :clap: :clap: :clap: 

The only other thing I think we'd want is to create a continuous deployment workflow, where PRs that get merged into a specific branch will be deployed as releases to GitHub and NPM. I can guide you through how we did this for the monorepo if you'd like, just DM me to setup a time to chat :D
