### ISSUE TITLE
EthereumPlugin calls using provider associated with a chainId?

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#337]
It would be useful if the Ethereum plugin's EthereumConfig could accept a chainId to associate with a particular network, which would then override the network name when the plugin determines which connection to use. I don't know how this would work when a user wants to have two networks with the same chain id. Maybe this could be an argument in the ethereum plugin function call.

I'll explain why I think it would be helpful.

This is our EthereumConfig for testing the uniswap api:
```
{
  networks: {
    testnet: {
      provider: ethereum
    },
    MAINNET: {
      provider: "http://localhost:8546"
    },
  },
  defaultNetwork: "testnet"
}
```

The capitalization of MAINNET here is necessary. If we want to call an ethereum query on the MAINNET provider, we have to pass the case-sensitive network name we use in our redirects.

In the uniswap api, we have an enum for ChainId that looks like this:
```
enum ChainId {
  MAINNET
  ROPSTEN
  RINKEBY
  GOERLI
  KOVAN
}
```

This enum is used to associate a chain id with each token in the uniswap api. We can pass the enum string to the Ethereum plugin to make calls and it works fine. 

However, it would be better if we could pass a chain id like 1 for mainnet, regardless of the name we use in redirects for two reasons:
(1) when we implement our redirects in the uniswap interface, we will need an entry for mainnet and each testnet chain even though we are passing in the same variable for our provider
(2) a user might have another API that assumes different names are used, which would require an additional set of entries in the redirects array

```
const activeNetwork = useActiveNetwork()

{
  networks: {
    MAINNET: {
      provider: activeNetwork
    },
    RINKEBY: {
      provider: activeNetwork
    },
    ROPSTEN: {
      provider: activeNetwork
    },
    KOVAN: {
      provider: activeNetwork
    },
    GOERLI: {
      provider: activeNetwork
    },
  },
  defaultNetwork: "MAINNET"
}
```

An alternative solution could be to require network names follow a standard. Maybe names should be the chain id numbers themselves (e.g. "1" instead of "MAINNET")?

**Comment by dOrgJelli** [comment]
A fix to support this use-case has been implemented, see code here: https://github.com/Web3-API/monorepo/blob/52504c5f2b7301cbe409922a653082b451b431c1/packages/js/plugins/ethereum/src/Connection.ts#L42-L61
