### ISSUE TITLE
unknown wake state 0 exception

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#369]
Steps to reproduce:
1. checkout the monorepo branch uniswap-web3api
2. nvm use && yarn reset
3. in a separate folder, checkout the unknown-wake-state branch of the [uniswap-interface repo](https://github.com/Web3-API/uniswap-interface/tree/unknown-wake-state)
4. change the directory locations of the the ethereum and sha3 plugins in the uniswap-interface package.json file, making sure they point to ethereum and sha3 plugins from the monorepo branch uniswap-web3api.
5. yarn && yarn prestart && yarn start
6. change the output token until the exception is thrown

The exception is caused by the w3PairAddress function found within src/web3api/tradeWrappers.ts. The function is used within the w3InvolvesAddress function found in src/state/swap/hooks.ts.

![Screenshot from 2021-06-08 15-08-14](https://user-images.githubusercontent.com/39842820/121250959-f4db4a00-c86b-11eb-96c2-e41e3a8c20f4.png)

**Comment by dOrgJelli** [comment]
Fixed this in the Uniswap V2 PR. Here's the fix: https://github.com/Web3-API/monorepo/commit/e8d5eabf23b6c8f70430a0cb40acd1f9882030d9
