### ISSUE TITLE
web3api.build.yaml Shouldn't Require `config` property

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#383]
Currently, the `config` property is required, but it shouldn't be. In the case where a developer wants to write a custom Dockerfile, the config isn't needed.

**Comment by krisbitney** [comment]
I've been looking at this and I don't think the config property is required. I can build just fine without it. 

However, an exception is thrown suggesting the config property is required when you try to build without it after first building with it. So let's say you first run w3 build with config set. This generates the .w3 folder used to build the API. If you then try building from a customer Dockerfile, an exception will be thrown saying the config property is required (fails jsonschema validation). But if you delete the .w3 folder, you can once again build just fine from a custom Dockerfile. 

I am currently trying to make sure the presence of a .w3 folder doesn't affect a user's ability to build from a custom Dockerfile.
