### ISSUE TITLE
bug encountered during LP livestream: "cannot read manifest of undefined" during cli command "create"

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#400]
Some developers at our launch partner Squad.Games encountered a bug during their livestream. They CLI threw an exception when they tried to run `npx @web3api/cli create api assemblyscript <project-name>` as described in our docs. When they tried to name their project "api", the command failed. They successfully created a project in a folder named "test". They were able to successfully create a project named "api" when they went up another level in their directory, and hypothesized that something in their folder was confusing the CLI.

From Jesse: 
> We discovered what we think might be a bug at around 15:00 in.
> essentially the create command worked outside of our existing monorepo but not inside it. I ended up creating it outside the folder and copying it in (and getting a nice opportunity to show of my zsh tab expansion setup!)

I recommend watching the livestream from about 5 minutes in until about 16 minutes in. 
Livestream link: https://www.twitch.tv/videos/1072603812

Screenshot of exception and prior terminal commands (livestream time 7:00): 
![Screenshot from 2021-06-30 18-04-06](https://user-images.githubusercontent.com/39842820/124042138-d8937e80-d9cd-11eb-9a13-06ea7c815d80.png)

Screenshot of when it worked correctly for project name "test" (livestream time 10:00):
![Screenshot from 2021-06-30 18-11-29](https://user-images.githubusercontent.com/39842820/124042559-b5b59a00-d9ce-11eb-9ab9-c78f7c1bc022.png)

Screenshot of when it worked correctly for project name "api" (livesream time 14:00): 
![Screenshot from 2021-06-30 18-23-11](https://user-images.githubusercontent.com/39842820/124043305-5eb0c480-d9d0-11eb-8ef0-b7b776a70f86.png)

**Comment by dOrgJelli** [comment]
Cannot repro. I think they might have an old version of the CLI added in their monorepos node_modules, or installed globally. Closing for now.

**Comment by dOrgJelli** [comment]
Also I'm in contact w/ the LP who ran into this, and have talked to them about the issue.
