### ISSUE TITLE
Support `getImplementations(interfaceUri)` in Wasm

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#405]
Add an interface to generated Wasm code which allows wrappers to `getImplementations` of a given interface URI.

This work is waiting on the Asyncify issue to be completed: https://github.com/polywrap/monorepo/issues/158

# Potential Dev Exp (Assemblyscript)
```typescript
import { client } from "./w3";

const impls = client.getImplementations("ens/interface.eth");

for (const impl of impls) {
  client.query({
    uri: impl,
    query: `query { method(...) }`
  });
}
```

**Comment by nerfZael** [comment]
For APIs I think it would be good to enforce more strict rules but without losing flexibility. 
So, I would like to move away from using loose string URIs like: 
```typescript
client.getImplementations("my-interface.eth") 
``` 
and
```typescript
client.query("my-api.eth") 
```
And rather use something like: 

```typescript 
client.getImplementations(interfaces.myInterface) 
``` 
and
```typescript 
client.query(apis.myApi) 
``` 
with the manifest: 
```
dependencies
  api
    myApi: my-api.eth 
  interface 
    myInterface: my-interface.eth 
``` 

or maybe better with helper functions: 
```typescript 
import { getImplementations, query } from "./w3/helpers"; 

getImplementations(interfaces.myInterface) 
query(apis.myApi) 
``` 
or with dependency generated api wrappers: 
```typescript
import { myApi, myInterface } from "./w3/dependencies"; 

myInterface.getImplementations() 
myApi.query()
``` 

(the cli would use the manifest dependencies to generate code, either the helper (2. example) or the dependency(3. example) types

The idea is to constrain devs to declare the APIs or interfaces they want to invoke, in the manifest 
I think it would result in APIs with less side effects (like querying a dependency api the user didn't know about), and 
with more descriptive manifests that tools can use, like clients or the hub. 
Ofc, it doesn't have to be declared in the manifest, we could have like a package.json which I like a lot more.

**Comment by nerfZael** [comment]
This:
```typescript
#import { Query } into Interface from "interface.eth"
``` 

```typescript
Interface_Query.someMethod(...);
```

should probably show a compile error for the second part. This would require the build process to know if the imported API is an interface, of course.

**Comment by nerfZael** [comment]
In general, I feel like accessing the client object directly, eg:
```typescript
client.geImplementations()
```
 is a bad pattern to have. I feel like the API shouldn't know about the client.

**Comment by nerfZael** [comment]
Notes after call with @dOrgJelli and @Niraj-Kamdar :
Downsides of the naive approach:
  - can't understand the dependency graph!
  - trace-ability / debug-ability
  - - "What interfaces does this wrapper need / request?"
  - - "What modules will this wrapper query at run-time?"
  
Desired approach:
Example schema:
```typescript
#import { Query } into Interface from "ens/interface.eth"
#use { getImplementations } for Interface

type Query implements Interface_Query {

}

# TODO:
# - don't allow type.name == namespace.name
type Interface {
  foo: String!
}
```
Add the custom "use" command for an already imported interface namespace (Interface)
Additionally, the toolchain needs to support a rule to not allow type names to be named the same as imported namespaces.

Usage example:
```typescript
import {
  Interface,
  Interface_Query,
  Interface_Mutation
} from "./w3";

function foo() {
  const impls: string[] = Interface.getImplementations()

  for (const impl of impls) {
    const query = new Interface_Query(impl);

    query.someMethod({
      foo: 3
    });

    const mutation = new Interface_Mutation(impl);

    mutation.someMethod({
      bar: "string"
    })
  }

  const custom = new Interface_Query("ens/custom-impl.eth");

  custom.someMethod({
    foo: 3
  });
}

class Interface {
  uri: string = "ens/interface.eth"

  static public getImplementations() {
    __w3_getImpls(this.uri)
  }
}
```
Add the class interface which has the uri property and the getImplementations function which returns a uri array of implementations for that interface.
Enforce checking whether the queried implementation really is an implementation specified in the client config.

**Comment by Niraj-Kamdar** [comment]
I have created  rough dev specs, let me know if I missed anything or got it wrong:
1. Create a new typedef for `use` syntax in typeInfo and extract logic for it.
3. Create mustache template for the Interface codegen in `/bindings/wasm-as`
4. write binding logic in `/bindings/wasm-as`.

**Comment by dOrgJelli** [comment]
Hey @Niraj-Kamdar, yes this is generally correct. Here's a bit more details on how to execute this:

1. Implement the concept of "use" & "getImplementations" within the TypeInfo data model. One suggested path to do this would be:
[here](https://github.com/polywrap/monorepo/blob/prealpha/packages/schema/parse/src/typeInfo/definitions.ts)
```typescript
...
export interface ImportedQueryCapabilityDefinition {
  getImplementations?: boolean;
}

export interface ImportedQueryDefinition
  extends GenericDefinition,
    ImportedQueryCapabilityDefinition,
    ImportedDefinition,
    WithComment {
  methods: MethodDefinition[];
}
...
```

2. Extract these "use" capability statements from the schema:
[here](https://github.com/polywrap/monorepo/blob/prealpha/packages/schema/compose/src/index.ts)
```typescript
for (const name of Object.keys(schemas)) {
    const schema = schemas[name];

    typeInfos[name] = await resolveImportsAndParseSchemas(
      schema.schema,
      schema.absolutePath,
      name === "mutation",
      resolvers
    );

    typeInfos[name] = await resolveUseStatements(
      schema.schema,
      typeInfos[name]
    );
  }
```
where `resolveUseStatements` extracts the `#use` statements using a regex string, and adds the capabilities being requested to the provided typeinfo. The newly modified typeinfo would be returned.

I'd suggest adding the `resolveUseStatments` function to the `resolve.ts` file.

3. Create a new templates folder within the `wasm-as/templates/imported/` folder in the schema bind package named `interface` where we generate an index.ts file for a provided interface, containing a class w/ static methods for the capabilities being used. For example `getImplementations`.

4. Modify the `packages/test-cases/cases/bind/sanity/output` & `input` files to include this new feature. I'd recommend doing this step FIRST so you can define what you'd want the generated code to look like. The move up to step 3 next, so you can understand what shape you'd need the TypeInfo struct to be for easy codegen. The provided TypeInfo addition above may not suite your needs the best, so some other addition to TypeInfo may be needed.

5. Create an e2e test-case where this is used. I'd recommend running this within the JS client's `Web3ApiClient.spec.ts` test cases, where you're building a real API, and calling a function that does this functionality.

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli Why are we associating `ImportedQueryCapabilityDefinition` with just `ImportedQueryDefinition `?
```ts
export interface ImportedQueryCapabilityDefinition {
  getImplementations?: boolean;
}
```
What if user only imports `Object` or `Enum` into namespace?

**Comment by dOrgJelli** [comment]
I don't see a use for `getImplementations()` when the interface only contains an `Object` or `Enum` (for example). The only use I see is when there's a `Query` or `Mutation` interface that you'd like to send function calls to. If there is a use-case I'm missing, can you elaborate @Niraj-Kamdar?

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli In this template:
```ts
class Interface {
  uri: string = "ens/interface.eth"

  static public getImplementations() {
    __w3_getImpls(this.uri)
  }
}
```

How do we get `__w3_getImpls` function? Is it implemented? If yes then how can I import it?

**Comment by Niraj-Kamdar** [comment]
I have implemented `resolveUseStatements` and while testing I am using `use...for...` syntax in `query.graphql` which will correctly resolve it with `getImplementations: true` attribute but since I am not using `use...for...` syntax for `mutation.graphql` and both of them share same type (Ex: TestImport_Query), I am getting following error:
```
      107 |         `combineTypeInfo found two types by the same type that are not equivalent.\n` +
      108 |           `Type: "${value.type}"\nObject A: ${destType}\nObject B: ${valueType}`
      109 |       );
```

**Comment by dOrgJelli** [comment]
> @dOrgJelli In this template:
> 
> ```ts
> class Interface {
>   uri: string = "ens/interface.eth"
> 
>   static public getImplementations() {
>     __w3_getImpls(this.uri)
>   }
> }
> ```
> 
> How do we get `__w3_getImpls` function? Is it implemented? If yes then how can I import it?

No this is not implemented yet. You'd need to add this to the Wasm boundary's imports in the client & wasm-as runtime here:
- https://github.com/polywrap/monorepo/tree/prealpha/packages/js/client/src/wasm
- https://github.com/polywrap/monorepo/tree/prealpha/packages/wasm/as/assembly

**Comment by dOrgJelli** [comment]
> I have implemented `resolveUseStatements` and while testing I am using `use...for...` syntax in `query.graphql` which will correctly resolve it with `getImplementations: true` attribute but since I am not using `use...for...` syntax for `mutation.graphql` and both of them share same type (Ex: TestImport_Query), I am getting following error:
> 
> ```
>       107 |         `combineTypeInfo found two types by the same type that are not equivalent.\n` +
>       108 |           `Type: "${value.type}"\nObject A: ${destType}\nObject B: ${valueType}`
>       109 |       );
> ```

interesting, I'm unsure exactly in what context this error is being thrown. Could you show me this over a quick call?

**Comment by Niraj-Kamdar** [comment]
If there are multiple schemas Ex: schema for query and mutation then we are checking if its definition is equal but in case of `getImplementations` if we are just using it in one schema and not in others, then it will throw the below error. I am temporarily working around this by patching it but we do need a better solution 

https://github.com/polywrap/monorepo/pull/516/files#diff-366a7f3cad15ba4509b68c66eb64793ad19edfd9fa4e186057fbdd53153fc843

Also do we just want to check generic definition properties or all properties?

**Comment by Niraj-Kamdar** [comment]
Also, I think it would make more sense to have it under `TestImport` directory instead of `TestImport_Query`

**Comment by Niraj-Kamdar** [comment]
I have some questions regarding design of getImplementations and capabilities in general.

1. Should every capability have modules?
```
@capability(
type: <cap-type>,
modules: ["query", "mutation"] 
)
```
2. What does it mean to have modules in `getImplementations`? 
3. I believe we should have separate class with `namespace` as its name for the capabilities.

Example:
##### GraphQL schema
```graphql
# import { Query } into Interface from "...";
# use { getImplementations, something, somethingElse } for Interface;
```
##### Template 
```ts
import {
  w3_getImplementations,
  // other necessary imports .....
} from "@web3api/wasm-as";

export class {{namespace}} {
  uri: string = "{{uri}}"

  {{#capabilities}}
  {{#enableCapability}}{{type}}{{/enableCapability}}
  {{/capabilities}}
}
```

> Here {{#enableCapability}} is a mustache function which takes capabilityType as arg and render the template according to capability.

##### Rendered example
```ts
import {
  w3_getImplementations
} from "@web3api/wasm-as";

export class TestImport {
  uri: string = "testimport.uri.eth"

  public static getImplementations() {
    return w3_getImplementations(this.uri);
  }
  public static something() {
    ...
  }
  public static somethingElse() {
    ...
  }
}
```

I am thinking about putting this into its own directory under `imported` directory. If we put this inside `imported/query-type` there can be name collisions between classes in different Invokable modules. 

A possible use of modules params in capability can be, we may want to feed it to `enableCapability` module to change some behaviour but I don't think it's the case with `getImplementions`. Let me know if you think otherwise.

**Comment by dOrgJelli** [comment]
Just had a call with @Niraj-Kamdar, and here's what we came up with.

**TypeInfo**
```typescript
interface TypeInfo {
  objectTypes: ObjectDefinition[];
  enumTypes: EnumDefinition[];
  queryTypes: EnumDefinition[];
  interfaces: {
    uri: string;
    namespace: string;
    capabilities: {
      getImplementations?: {
        enabled: boolean;
        modules: InvokableModules[];
      };
    };
  }[];
  importedObjectTypes: ObjectDefinition[];
  importedEnumTypes: EnumDefinition[];
  importedQueryTypes: QueryDefinition[];
}

/*
interfaces: [
  {
    uri: "...",
    namespace: "Interface",
    capabilities: {
      getImplementations: true,
    },
  }
]
*/
```

**Mustache Template**
```mustache
import {
  w3_getImplementations,
  // other necessary imports .....
} from "@web3api/wasm-as";

export class {{namespace}} {
  uri: string = "{{uri}}"

  {{#capabilities}}
  {{#getImplementations}}
  export function getImplementations()
  {{/getImplementations}}
  {{/capabilities}}
}
```

**User Schema**
```graphql
# import { Query } into Interface from "...";
# use { getImplementations, something } for Interface;
# use { getImplementations } for Something

type Query {

}
```

**Built Schema**
```graphql
type Query @imports(
  types: [
    "Interface_Query"
  ]
) @capability(
  namespace: "Interface",
  capability: "getImplementations"
) {

}

type Interface_Query {

}
```

**Comment by dOrgJelli** [comment]
Closed in: https://github.com/polywrap/monorepo/pull/516

Thank you @Niraj-Kamdar !!!
