### ISSUE TITLE
Use Logger Interface In Wasm

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#406]
Currently for the `console` wrapper, we query the `js-logger` plugin directly. Instead of this, to make it "platform agnostic" and not specific to JS, we should:
1. Implement a `log` interface in the Wasm code generation folder.
2. When a developer calls `log.info("message")` (for example), the function should iterate through all implementations of the `logger.core.web3api.eth` interface, and log an info message.

Depends on: https://github.com/polywrap/monorepo/issues/405

# Potential Dev Exp (Assemblyscript)
```typescript
import { log } from "./w3";

log.info("message");
log.error("message");
log.debug("message");
log.warning("message");
```

**Comment by Niraj-Kamdar** [comment]
@dOrgJelli How should we fetch implementations of `logger.core.web3api.eth`? Should we keep them in default client config. (user can overwrite though)
Do we want to log message using each implementations?
It maybe useful in case of multiple log streams. Ex: one logger logs to console, while another logs to cloud logger or file.

**Comment by dOrgJelli** [comment]
@Niraj-Kamdar we should use the [w3_getImplementations](https://github.com/polywrap/monorepo/blob/prealpha/packages/wasm/as/assembly/get-implementations.ts) helper function in the Wasm runtime.

Yes, we should have 1 logger already defined by default in the client config.

Yes we want to log using each implementation, for the exact reason you mentioned (multiple logging streams).

**Comment by cbrzn** [comment]
This can also be closed since we have the `logger` wrapper (which uses the JS plugin implementation) and can be imported?

**Comment by Niraj-Kamdar** [comment]
Let's close this :)
