### ISSUE TITLE
Cross Module Dependencies

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#41]
Modules can query other modules just like an application queries modules:
```
query({
  uri: "latest.ethereum.web3api.dev",
  query: `mutation { sendTransaction(
    address: "0x...",
    method: "foo(uint256,address)",
    args: [55, 0x...]
    ) { tx { hash } }
  }`
})
```

And in the client it can filter for these domains and choose to send them to local modules if it has some. This way we don't need to implement it in WASM, and can instead use a module in the client language to do these requests.

**Comment by dOrgJelli** [comment]
const client = new Web3API({
  resolvers: [
    {
      uri: "v1.api.ethereum.*",
      resolver: new EthereumProxy(...)
    },
    (uri: string, query: string): any | undefined => {
      if (uri.contains("ethereum")) {
        // TODO: call into JS module
        return result;
      } else {
        return undefined;
      }
    }
  ]
})

**Comment by dOrgJelli** [comment]
Register Dependencies:
```typescript
export function register() {
  // TODO: "these are my dependencies"
  _w3_register_dep("v1.api.ethereum.web3api.eth");
}
```

**Comment by Remscar** [comment]
Working on the resolver idea

**Comment by dOrgJelli** [comment]
This has been completed in prealpha-dev
