### ISSUE TITLE
TypeScript dApp Code Generator

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#487]
Generate TypeScript typings for dApp developers.

**Comment by krisbitney** [comment]
Should this feature be:
1. its own CLI command
2. an option in the codegen command
3. just the mustache template and codegen script (if so, where should i put them?)

I have a mustache template and codegen script set up in the ts-types-codegen branch. I also added a mustache function to make sure the types were formatted correctly. I just need to know how the user experience should be.
