### ISSUE TITLE
Use Witx For Web3 WASM Interface Definitions

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#5]
WASI has created a WASM interface definition markup language that allows you to describe portable interface definitions using WASM Interface Types. You can see WASI's Witx interfaces here: https://github.com/WebAssembly/WASI/tree/master/phases/snapshot/witx

and learn more about why Witx is necessary here: https://youtu.be/LCA9NnH7DxE

It's not currently clear to me if AssemblyScript supports WASM Interface Types, more available here: https://github.com/AssemblyScript/working-group/issues/13

I think the goal of "making the Web3API WASM interface runtime agnostic" can be achieved without the above... all TBD.

**Comment by dOrgJelli** [comment]
Super useful example demonstrated here: https://youtu.be/9py3lqYoihc?t=998

**Comment by dOrgJelli** [comment]
For example, trace how `path_create_directory` is implemented in WASI (Assemblyscript's WASI API -> wasmtime in Rust):
- https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md
- https://github.com/jedisct1/as-wasi/blob/4d63b96e2efe95ac6dbf76263546867b2371054c/assembly/as-wasi.ts#L516

**Comment by dOrgJelli** [comment]
Note: Witx can be used to generate types in all Web3API WASM run-times (Assemblyscript, etc) and client libraries (Javascript, etc).

**Comment by mpetrunic** [comment]
> Note: Witx can be used to generate types in all Web3API WASM run-times (Assemblyscript, etc) and client libraries (Javascript, etc).

Could you point us to tool that can do that?
I've only found this rust create to validate and generate rust code maybe: https://github.com/WebAssembly/WASI/tree/cbfa8b353dc612521231a64ce8e6fec6af55b561/tools/witx

**Comment by dOrgJelli** [comment]
That's the only tool I've found as well. Maybe the best way to do this is to just document the interfaces in the spec, and not bother with Witx since the tooling is lacking and we'd have to create our own.

**Comment by dOrgJelli** [comment]
Or we could just have the Witx file along-side the specification, and folks can use it if they'd like (once the tooling is improved).

**Comment by mpetrunic** [comment]
We were testing. We could write witx and generate markdown(supported by the tool) from it. Looks clean

**Comment by dOrgJelli** [comment]
Amazing, let's do that!

**Comment by mpetrunic** [comment]
Should we add instructions how to generate them locally and add CI check to make sure they are up-to-date?

cc @mpetrun5

**Comment by dOrgJelli** [comment]
Yes that sounds good @mpetrunic, and yes I think CI integration would certainly be useful. How would this work best? Maybe generate + diff? Or generate + push artifacts?

**Comment by mpetrunic** [comment]
I think we should generate locally and CI should generate and check for diff (generated files not updated). Reason for this is that it should be easier to review generated markdown than to figure out what witx would generate if we merge it to master. 

Other option is to generate and commit on every push but I feel like we could end up with bunch of CI commits

**Comment by dOrgJelli** [comment]
Yep sounds good, let's just diff

**Comment by dOrgJelli** [comment]
Completed here: https://github.com/Web3-API/specification/pull/7
