### ISSUE TITLE
Detect GraphQL cycles from TypeInfo instead of GraphQL AST

### ISSUE THREAD

**Issue by namesty** [Web3-API/prototype#509]
Currently, the package being used to detect cycles in GraphQL schemas is: https://github.com/polywrap/graphql-cycles-detector.

It works by analyzing the AST of the GraphQL schema taken as input. It should be updated to take a TypeInfo instead and analyze cycles from it.

**Comment by dOrgJelli** [comment]
I think for this update, we should move the resulting code into a new package called `@web3api/schema-inspect`, where we define new functions that can be used to "inspect" the TypeInfo structure in various ways.

**Comment by dOrgJelli** [comment]
This new package would live in the folder "packages/schema/inspect/"
