### ISSUE TITLE
Question: should we disable CI run on any branch other than master?

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#528]
When we create a PR from a branch from upstream to the master, it runs CI for both pull-request and push which seems redundant and time-consuming. 

A solution would be to turn off the CI for pushing commits on any branch other than `master`(prealpha or prealpha-dev in our case).

**Comment by dOrgJelli** [comment]
Yes definitely, this is a great point, we should do this.

**Comment by dOrgJelli** [comment]
Removed push CI runs, only PRs trigger them now. We can iterate on this in the future to support "release branch only push CI runs", but for right now it should be expected to only PR into release branches, and not push.
