### ISSUE TITLE
Modularize the Web3API Class

### ISSUE THREAD

**Issue by Remscar** [Web3-API/prototype#58]
[Retroactively created issue]

Most of the logic for Web3API is inside of a single class. The logic should be modularized out into discrete components which are leveraged as needed. This will reduce tech debt, code smell, and the time it takes for future iterations. Code will also be easier to test and maintain, making it easier to add on future features.

The proposed structure:

- Client: This is the dev/user entry point into using Web3API's
- URI Resolvers: This is what resolves a query URI into an actual Web3API
- Web3API Definitions: This is a cache of data required to create an instance of a Web3API for usage.
- Web3API: This is an actual Web3API, which can be queried by a user.

The end user will never interact with anything but the `Client`

**Comment by dOrgJelli** [comment]
Closed in prealpha-dev branch
