### ISSUE TITLE
Add Client "resolveUri" Method

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#583]
Add a utility method to the client for resolving a URI. The intention is for this method to be used to introspect the URI resolution process.

@nerfZael is working on a new URI resolver, and would like to write tests verifying it's working correctly "under the hood". This method would enable that.

The developer experience should be something like:
```typescript
resolveUri(uri: string | Uri) => ResolveUriDertails[]
```
where `ResolveUriDertails` could take the form of:
```typescript
interface ResolveUriDertails {
  // The uri-resolver used
  uriResolver: Uri;

  // Input & results of the `tryResulveUri` method
  tryResolveUri: {
    input: {
      authority: string;
      path: string;
    };
    result: {
      uri?: string | null;
      manifest?: string | null;
    };
  }
}
```

The array of details structures represents the "resolution chain" that occurs when the resolve URI process is undergone.

Additional information can be added to this details structure as needed, such as:
- timings
- errors

**Comment by ramilexe** [comment]
Hi @nerfZael @dOrgJelli 
Will this method return `ipfs` hash somethere?

**Comment by dOrgJelli** [comment]
@nerfZael is working on this currently @ramilexe. Yes the result will return the URI of the package. Here's the WIP signature of the function: https://github.com/polywrap/monorepo/blob/1c85bce238cb56f28a456f554212a0fdcb4cfa71/packages/js/client/src/Web3ApiClient.ts#L405-L414
