### ISSUE TITLE
cli should have an option to initialize polywrapper from an interface

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#585]
Currently we just support creating very basic boilerplate using cli:
`npx w3 create api assemblyscript <name>`

We should have option to specify interface or list of interfaces that we want to implement in the polywrapper while initializing. This will help improve developer experience.

### For Example:
If we have interface `xyz.eth` with following schema: 
```graphql
type Query {
  getSomething(...): Something!
  ...
}
```

and interface `abc.eth` with following schema:
```graphql
type Mutation {
  setSomething(...): Something!
  ...
}
```
then this command should create following schema and basic typescript boilerplate

#### Command: 
```console
 npx w3 create api assemblyscript <name> --interfaces "xyz.eth, abc.eth"
```
#### Schema:
```graphql
type Something implements XYZ_Something {...}

type Query implements XYZ_Query  {
  ...
}
type Mutation implements ABC_Mutation {
  ...
}
```

#### index.ts
```ts
export function getSomething(input: Input_getSomething): Something {}
export function setSomething(input: Input_setSomething): Something {}
```

**Comment by dOrgJelli** [comment]
This is really interesting @Niraj-Kamdar! What do you think about adding support for generic user-defined project templates instead?

That way someone could write `w3 create @npm-org/package-name 1.0.0-optional-version`

Creators of interfaces could publish their own project templates for their users to use.

Also it might be best to not just support NPM, and also support repository & archive (zip) URLs

**Comment by Niraj-Kamdar** [comment]
I agree on npm or repository templates.

**Comment by Niraj-Kamdar** [comment]
I am increasing priority since this is really needed for `defiwrapper`. Since it heavily rely on interface-implementations and changing `package.json` and not getting better boilerplate is making dev experience really bad.

**Comment by Niraj-Kamdar** [comment]
This can also be used for Tezos template: #666
