### ISSUE TITLE
Allow for the usage of JavaScript based Web3API's

### ISSUE THREAD

**Issue by Remscar** [Web3-API/prototype#59]
In some cases it may be easier for developers to create a Web3API that is actually in JavaScript instead of WASM. As far as the user is concerned, it is interacted with the same way that any other Web3API is, however in the backend, JavaScript code is actually ran instead.

Since runtime code execution is not allowed, the JavaScript Web3API's must be defined on build, and not during the runtime. This means that the end-user will have to configure which JavaScript Web3API's are allowed to be used. This can be done by linking a specific URI to a JavaScript Web3API.

**Comment by dOrgJelli** [comment]
These are currently being referred to as "Client Plugins", and can be used with any client like so:
```typescript
import { EthereumPlugin } from "ethereum-web3api-js"
import { Web3APIClient } from "@web3api/client-js"

const ethereum = new EthereumPlugin({ provider: window.web3 });

const client = new Web3APIClient({
  plugins: [
    ethereum
  ]
})
```

These plugins can specify what URIs they intercept via regex. For example, for ethereum it might look like:
```typescript
public getUris(): RegExp[] {
  return [
    // Matches: ethereum.eth
    // Matches: api.ethereum.web3api.eth
    /(.*[\.])?ethereum[\.].*/,
    // Matches: w3://ethereum
    /w3:\/\/ethereum/
  ];
}
```

You can see JS plugins that've been created for Ethereum, IPFS, and The Graph here: https://github.com/Web3-API/prototype/tree/issue-28/packages/client-js-plugins

**Comment by dOrgJelli** [comment]
Completed in prealpha-dev branch
