### ISSUE TITLE
Bug: combined schemas can have types with duplicate properties if implementing an interface

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#601]
This bug leads to thrown exceptions when trying to use the combined schema for code generation. The issue seems to be that, in the combined schema, a type which implements an interface will declare the interface's properties and also implement the interface, implicitly declaring the properties twice. See example below. 

My schema:
```
# Options to specify when claiming rewards.
type ClaimOptions {
  tokenId: BigInt! # The id of the NFT
  recipient: String! # Address to send rewards to.
  amount: BigInt # The amount of `rewardToken` to claim. 0 claims all.
}

type FullWithdrawOptions implements ClaimOptions {
  owner: String! # Set when withdrawing. The position will be sent to `owner` on withdraw.
  data: String #  Set when withdrawing. `data` is passed to `safeTransferFrom` when transferring the position from contract back to owner.
}
```
Combined schema after build:
```
type ClaimOptions {
  tokenId: BigInt!
  recipient: String!
  amount: BigInt
}

type FullWithdrawOptions implements ClaimOptions {
  owner: String!
  data: String
  tokenId: BigInt!
  recipient: String!
  amount: BigInt
}
```
Exception thrown:
<img width="930" alt="Screen Shot 2022-01-06 at 3 26 58 PM" src="https://user-images.githubusercontent.com/39842820/148432336-9e4eb8ec-2335-453f-8ab5-be1791fc61ae.png">

**Comment by dOrgJelli** [comment]
@krisbitney can you provide full repro steps for this? I think the problem may be that you're trying to "compose" a schema that's already been composed. Instead you should go straight to parse.

Confusing... I know... this is another oddity of working with the GraphQL AST directly, and needing to have a 3 stage schema pipeline (user-schema, built-schema, typeinfo).

**Comment by krisbitney** [comment]
> @krisbitney can you provide full repro steps for this? I think the problem may be that you're trying to "compose" a schema that's already been composed. Instead you should go straight to parse.
> 
> Confusing... I know... this is another oddity of working with the GraphQL AST directly, and needing to have a 3 stage schema pipeline (user-schema, built-schema, typeinfo).

Thanks. I was trying to use codegen on a composed schema. I'll see what I can do to skip to parse.
