### ISSUE TITLE
Rename TypeInfo `queryTypes` to `moduleTypes`

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#613]
In an effort to continue moving in the direction of custom-user-defined-modules, and away from Query/Mutation query modules, we can start by simply renaming `queryTypes` to `moduleTypes` within the TypeInfo datamodel.

More discussion on this here: https://discord.com/channels/796821176743362611/908544308876050515/933677270424514580

**Comment by RishiKumarRay** [comment]
can i raise a PR on this?

**Comment by Niraj-Kamdar** [comment]
> can i raise a PR on this?

@RishiKumarRay That'd be super helpful. Go ahead and knock it out!

**Comment by RishiKumarRay** [comment]
@dOrgJelli please review the PR #614

**Comment by dOrgJelli** [comment]
Responded @RishiKumarRay
