### ISSUE TITLE
Build-Time Improvement: Don't Overwrite Build Image Cache

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#616]
Currently by default, the CLI assigns a single name to the docker build-image it constructs.

This causes a loss of caching when building 2 separate projects back to back, this is because the name is being re-used for two different project directories. The cache gets flushed because the source files are different in the project directory.

In order to fix this, we should prescribe a name to the build image. This image name can be found by:
- Looking at the build manifest's `docker.name` property
- Allowing the user to assign it via a command line argument
- Auto generating a random name

The build image's name can be cached in the CLI's `.w3/` archive folder.

**Comment by Niraj-Kamdar** [comment]
This would be really nice improvement for devs! I also noticed some issues due to it having same name in docker networks, apparently I need to prune docker network sometimes since it creates to network with the same name.
