### ISSUE TITLE
Separate Concerns, IPFS/ENS Plugins, URI Resolver Interface

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#622]
With the IPFS & ENS plugins, they both implement their respective core functionalities, along with implementing the URI Resolver interface methods.

This causes a "confusion of concerns", and leads to issues like the ones described in this thread: https://discord.com/channels/796821176743362611/908544308876050515/935542806418710548

We should create separate plugins for the IPFS & ENS URI-Resolvers, which depend on the IPFS & ENS wrappers within themselves.

**Comment by nerfZael** [comment]
> With the IPFS & ENS plugins, they both implement their respective core functionalities, along with implementing the URI Resolver interface methods.
> 
> This causes a "confusion of concerns", and leads to issues like the ones described in this thread: https://discord.com/channels/796821176743362611/908544308876050515/935542806418710548
> 
> We should create separate plugins for the IPFS & ENS URI-Resolvers, which depend on the IPFS & ENS wrappers within themselves.

They will depend on IPFS plugin and ENS wrapper, correct? @dOrgJelli 
Also, we need to add the FS URI Resolver to this list

**Comment by nerfZael** [comment]
Added this to the following story: https://github.com/polywrap/monorepo/issues/714

**Comment by nerfZael** [comment]
IPFS part is blocking: #717

**Comment by nerfZael** [comment]
Before this is tackled we should merge this PR: 
- [x] #620 
This will allow us to also rewrite the plugins with the new plugin experience

**Comment by dOrgJelli** [comment]
@nerfZael new plugin devexp has been merged, and will be in versions `0.0.1-prealpha.72`+
