### ISSUE TITLE
CLI: Use Commander in-place of GlueGun

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#628]
I recently saw a CLI that @nerfZael created using Commander, and thought the code-base looked much better than our GlueGun based CLI. I think it might be worth it to migrate our CLI's codebase to Commander. Thoughts?

**Comment by dOrgJelli** [comment]
https://github.com/tj/commander.js/

Example use-case: https://github.com/nerfZael/wrap-persistence-node/blob/c6c65bf441f91c768c2b75b634c1ab476a27b6ec/src/main.ts#L18

**Comment by Niraj-Kamdar** [comment]
I like commander more and also used it in both registry dev-cli and node. So, I am all up for it. I personally like the way it allow us to define command and function and chain it together.

**Comment by cbrzn** [comment]
This has also been addressed :-D
