### ISSUE TITLE
Support YAML for Recipe Scripts

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#629]
Currently recipe scripts are written in JSON, but I think for all user-defined POD files the CLI uses we should support both JSON & YAML. This is because YAML has many user-friendly features, and we would simply convert to JSON after it gets loaded from disk.

**Comment by Niraj-Kamdar** [comment]
I 100% agree on this. It'd really be nice to have comment support in the recipes. We can also add comment as a field in JSON recipes.
