### ISSUE TITLE
Create Easy Way to Invoke All Implementations

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#631]
In WASM we should be able to easily call a single interface method on all implementations, instead of iterating over each implementation.

Currently today, you have to:
```typescript
const uris = Interface.getImplementations()

for (const uri of uris) {
  const query = new Interface_Query(uris[0])
  query.method();
}
```

It'd be nice if we could simply call:
```typescript
Interface_Query.method(...)
```
and it would effectively do the same as the above code snippet.

NOTE: the current way of doing this would still be supported, this is simply a helper.

**Comment by Niraj-Kamdar** [comment]
This is a good addition.
