### ISSUE TITLE
Return [Error?, TData?] instead of { error?: Error, data?: TData } ?

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#638]
Should the Web3ApiClient `invoke` method return `[Error?, TData?]` instead of `{ error?: Error, data?: TData }`?

**Comment by Niraj-Kamdar** [comment]
Would it work on other clients implemented in different languages which aren't so lenient when it comes to type?

**Comment by dOrgJelli** [comment]
That's a great point @Niraj-Kamdar, no it would not. In my opinion I'm very "on the fence" about this change, and feel that the down-side you've brought to light is enough to make me think this is not a great idea.
