### ISSUE TITLE
Future Proof URI Resolution

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#64]
Currently, IPFS and ENS are supported by the client-js implementation. This is hard-coded, and should be modularized in some fashion. This way when a new URI scheme comes around, it can be automatically used by already released clients. Here's the proposed implementation for doing this:
1. Support IPFS resolution by default
2. Upload a mapping file to an IPNS location that can be updated in the future. This file will contain mappings from regex URI detectors, to WASM URI resolver modules.

In the client, the logic will change to:
1. Check to see if URI is IPFS compatible
2. If not, fetch mapping file from known IPNS location.
3. Iterate through all entries, seeing what regex matches the provided URI.
4. Fetch the URI resolution WASM module for that URI type.
5. Execute the known function on the module to fetch the IPFS hash for the provided URI.

**Comment by Remscar** [comment]
Going to investigate this.

**Comment by Remscar** [comment]
How does the client know of the IPNS locations? The user could provide the client with a list of IPNS locations to look.
This assumes that all URI resolutions will resolve into an IPFS hash. Is that an assumption we want to make, or should we leave it up to the URI Resolution WASM module to instead return a Web3API (module+manifest+schema+ect)?

**Comment by dOrgJelli** [comment]
There would be one known IPNS location for the mapping file. This would be hard-coded into all clients.

I'm debating making this an IPNS location or an ENS domain... benefit of ENS domain would be that it can be updated via DAO proposal.

**Comment by dOrgJelli** [comment]
This has been implemented in prealpha-dev
