### ISSUE TITLE
Update GraphQL Cycle Detection, Use TypeInfo

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#641]
The GraphQL cycle detection code should be re-written to use the TypeInfo data structure instead. This way it can be easily ported into new client languages, and no longer relies on the GraphQL AST.

**Comment by krisbitney** [comment]
Also see #509

**Comment by krisbitney** [comment]
Relatedly, @Niraj-Kamdar has pointed out that allowing GraphQL cycles can make additional data structures possible, such as linked lists, trees, and graphs.

**Comment by Niraj-Kamdar** [comment]
I think there maybe an issue with GraphQL cycle detector.
```
type A {
  arrA: [A!]!
}
```
The above type should be valid type without cycle since if we have a leaf with property `arrA = []` then the cycle breaks and it becomes valid.

**Comment by dOrgJelli** [comment]
This has been fixed in this PR @Niraj-Kamdar https://github.com/polywrap/monorepo/pull/685
