### ISSUE TITLE
Allow user to add recipes into build artifacts

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#648]
If we have recipes inside build artifacts, users can query recipes directly from network with following command: 
```
npx @web3api/ci recipes -e storage.eth
```
This will query fetch recipes.json from build artifact and execute it.
This can even be used in hub for standardise experience.

**Comment by dOrgJelli** [comment]
This is very cool, I'm all for this! Also note that we support the `queries:` property in the `web3api.meta.yaml` manifest file, which allows users to provide query fragments w/ descriptions. I think the query recipes should be thought of as a layer on-top of this, where a recipe could contain multiple combinations of individual query fragments.
