### ISSUE TITLE
Ethereum plugin - utils

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#657]
Implement util functions from ethers.js in the Ethereum plugin/wrapper

This is a blocker for the Registry wrapper since it depends on the following ethers.js utils:
- namehash
- solidityKeccak256
- formatBytes32String
- zeroPad
- concat

**NOTE:** It might be a good idea, performance-wise, for wrappers (like the registry wrapper) to implement the following on their own:
- formatBytes32String
- zeroPad
- concat

While the following should be used through the Ethereum plugin/wrapper:
- namehash
- solidityKeccak256

**Comment by namesty** [comment]
@dOrgJelli If we're implementing this wrapper now in Rust, should I just start porting this in Rust?

**Comment by dOrgJelli** [comment]
@nerfZael please see how the ENS wrapper implements namehash & keccak using the UTS46 & SHA3 plugins (soon to be rust wrappers)

@namesty the UTS46 & SHA3 wrappers have already been started. Ask @kobby-pentangeli for link to the branch
