### ISSUE TITLE
I want all of the naming to be consistent (e.g. nothing is named web3api any longer)

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#703]
Acceptance Criteria:
- [x] #732
- [x] #735
- [x] #736
- [x] #737
- [x] #738

**Comment by dOrgJelli** [comment]
Status update: I've assigned all sub-tasks, and moved to "in progress"

**Comment by Niraj-Kamdar** [comment]
What do we want to do with hub and registry? Will we be refactoring it?

**Comment by dOrgJelli** [comment]
Closing this for now, as the ENS wrappers will be migrated soon.
