### ISSUE TITLE
CLI-V1: Easy Installation

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#706]
- [x] Documentation on how to install the CLI
  - Install via NPM `npx @polywrap/cli` or `npm install @polywrap/cli` or `yarn add @polywrap/cli`
  - Project specific CLI installation & configuration
  - CLI will be available through the node.js compatible entry file named `polywrap` located in the `@polywrap/cli/bin/polywrap` folder

**Comment by dOrgJelli** [comment]
Documentation here: https://docs.polywrap.io/guides/create-as-wrapper/project-setup#prerequisites

**Comment by dOrgJelli** [comment]
Marking this as "Needs Review", as I believe the documentation is satisfactory, but would like 3rd party approval.

**Comment by evanjacobs** [comment]
Here is a list of issues I discovered:

1. In the "Project Setup" section, the [Start Here](https://docs.polywrap.io/guides/getting-started/what-is-polywrap) link is broken
2. In the "Prerequisites" section, the [Integrate into a JS dapp](https://docs.polywrap.io/guides/create-as-wrapper/create-js-dapp/install-client) link is broken
3. There were a few issues with clarity/grammar.

I've submitted a PR that fixes these issues: https://github.com/polywrap/documentation/pull/138

**Comment by evanjacobs** [comment]
Otherwise, the documentation is easy to follow and I was able to follow the steps to install the CLI!

**Comment by dOrgJelli** [comment]
Amazing thank you @evanjacobs! With the PR merged, I'd like to call this one complete :clap:
