### ISSUE TITLE
CLI-V1: App Project Dev Exp

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#708]
- [x] `polywrap app codegen` [source](https://github.com/polywrap/monorepo/blob/prealpha/packages/cli/src/commands/app.ts)

Future Improvements:
 - [x] https://github.com/polywrap/monorepo/issues/729

**Comment by dOrgJelli** [comment]
Requesting Review: @nerfZael @krisbitney

**Comment by nerfZael** [comment]
Do all of the interfaces really need to extend "Record<string, unknown>"?

One thing I'd really love to see (and it's not listed in future improvements) is something like an `app init` or `app setup` command that auto-generates schema.graphql and web3api.app.yaml files. This would go a long way to helping users use this without having to dive into the docs.

Everything else looks good to me, this is a great first step

**Comment by krisbitney** [comment]
I used this in the uniswap front end interface demo and I was happy with the UX. LGTM!
