### ISSUE TITLE
I want to execute wrappers without possibility of centralized failure

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#716]
- [x]  [Implement comprehensive IPFS URI resolver configuration options](https://github.com/polywrap/monorepo/issues/717)

**Comment by nerfZael** [comment]
Blocked by #622

**Comment by dOrgJelli** [comment]
Story of stories @nerfZael? If so we can close.

**Comment by dOrgJelli** [comment]
This story is unblocked now
