### ISSUE TITLE
Implement comprehensive IPFS URI resolver configuration options

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#717]
Revisit resolution options (provider, parallel execution, etc...) for IFPS URI resolver and implement them as env variables

Before this task can be tackled, the IPFS part of the following issue needs to be implemented: https://github.com/polywrap/monorepo/issues/622

**Comment by dOrgJelli** [comment]
For the Plugin & Resolver:
- configure what you want from these two plugins
- Specify whether you want...
    - executed in parallel or serially
    - timeouts
    - etc

Implemented as environment variables.

**Comment by dOrgJelli** [comment]
Hey @nerfZael @pileks, what is the status on this issue?

**Comment by nerfZael** [comment]
> Hey @nerfZael @pileks, what is the status on this issue?

A PR is open, though I've yet to review it: https://github.com/polywrap/monorepo/pull/1060

**Comment by pileks** [comment]
Closing this issue as everything seems done.
