### ISSUE TITLE
Bug: reserved words filter replaces type names when a property has a reserved word as its name

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#721]
> Hi @krisbit, After the reserved words for target language PR,
> When we use reserved keyword inside a type:
> Ex: 
> type NewType {
>    type: String!
>    arg1: Int!
> }
> 
> then type here also gets replaced by the m_type and user needs to use m_type, is it desirable?
> 
> IMO we only need to replace name if it exist inside the method (Query/Mutation) since we define function for that in global scope. For other types it will exist inside object and user can use any reserved words inside object.
> 
> a
> { continue: 123 }
> a = {type: 11}
> { type: 11 }
> a = {function: 88}
> { function: 88 }
> a = {var: 122}
> { var: 122 }
> a = {const: 774}
> { const: 774 } 
>

**Comment by krisbitney** [comment]
This feature doesn't work with object literal syntax. Instead, we will need to add constructors to generated classes and use that syntax. Is that okay?
```
// doesn't compile
return {
 const: "foo"
};

// compiles
return new Result("foo");
```

**Comment by dOrgJelli** [comment]
What is the plan with this?

**Comment by krisbitney** [comment]
Closing this issue, as it can be superseded by https://github.com/polywrap/monorepo/issues/842
