### ISSUE TITLE
Define the "golden path" for free deployment

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#739]
# Golden Path: Free Deployment
## Path
* User deploys wrapper to `ipfs.wrappers.io` via the following persistence node feature:  
https://github.com/polywrap/nodes/issues/48
* Wrapper will be made available via IPFS for a short amount of time (further clarified in this SLA:  
https://github.com/polywrap/monorepo/issues/742)

## Definitions
* **Deployment:** add to IPFS for short-term

## Revisions
Revisions to this "golden path" will be made in future releases.

**Comment by dOrgJelli** [comment]
Requesting review: @nerfZael

**Comment by nerfZael** [comment]
LGTM
