### ISSUE TITLE
w3 app codegen generates code by default under  ./src/w3 but this should configurable by the user.

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#775]

**Comment by dOrgJelli** [comment]
@Niraj-Kamdar there's the `-c, --codegen-dir` option that you can use to specify a different directory.

I've also contemplated having this option specified in the manifest file, but unsure if that's necessary. Thoughts?

**Comment by dOrgJelli** [comment]
https://github.com/polywrap/monorepo/blob/4b52fdb32add542baaf7b88111485cee90e8d7c1/packages/cli/src/commands/plugin.ts#L46

**Comment by Niraj-Kamdar** [comment]
I'd also have it on manifest because it makes it easy for devs to configure it. We can have something similar to plugin -> `entrypoint`. 

This can be used on environments that users may or may not control - Ex: CI/CD where users don't have access to modify commands directly.

**Comment by Niraj-Kamdar** [comment]
Also generally we expose all the functionality that we provide as CLI command in the config file too.

**Comment by dOrgJelli** [comment]
This is now possible, closing.
