### ISSUE TITLE
CLI Codegen: require option to overwrite output directory; allow output to subfolder paths

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#801]
The CLI `w3 codegen` feature overwrites the target output folder, and can overwrite a project's root folder and all its contents if a naive user tries to set the output location there. I propose that an option be required to overwrite directories.

Relatedly, outputting files into hierarchical directories is not straightforward when writing custom codegen scripts.
`yarn w3 codegen -s ./scripts/meta.ts`
```
// outputs to default folder ./w3
renderTemplate("./meta-manifest.mustache", rootContext, "web3api.meta.yaml");

// throws "Failed to generate types: ENOENT: no such file or directory..."
renderTemplate("./meta-manifest.mustache", rootContext, "./subfolder/web3api.meta.yaml");
```

This cannot be rectified by ensuring the subfolder exists beforehand because codegen overwrites the target directory. Instead, users must set the output folder to the deepest subfolder and use relative pathing.

`yarn w3 codegen -s ./scripts/meta.ts -c ./w3/subfolder`
```
// outputs to ./w3
renderTemplate("./meta-manifest.mustache", rootContext, "./../web3api.meta.yaml");
```
It would be a better UX if users could specify sub-directories directly.

**Comment by dOrgJelli** [comment]
Hey @krisbitney, this should work now, would you mind giving it a try?

**Comment by krisbitney** [comment]
I tested it and it still does not work

**Comment by dOrgJelli** [comment]
Ah strange, okay adding this to the roadmap. Do you know what a fix would look like in terms of implementation details?

**Comment by krisbitney** [comment]
Okay, now that I've looked into it I can see what's going on. I didn't understand how the `writeDirectorySync` function in `@polywrap/os-js` works. It is possible to make a directory by inserting an entry with type "Directory" and nesting the "File" type within it. This is all the more reason that we need docs on codegen!

```
case "File": {
  writeFileSync(entryPath, entry.data);
  break;
}
case "Directory": {
  for (const subEntry of entry.data) {
    if (!existsSync(entryPath)) {
      mkdirSync(entryPath, { recursive: true });
    }
    outputDirectoryEntry(entryPath, subEntry);
  }
  break;
}
```

I think we can close this issue.
