### ISSUE TITLE
Wrapper package validation

### ISSUE THREAD

**Issue by nerfZael** [Web3-API/prototype#803]
This should be implemented either in core-js or as a separate js package.
Use cases: 
- Validate a package at a URI (ENS/IPFS/FS)
- Validate an in-memory package (list of files with names, extensions, sizes, contents as a buffer)

Validation parts:
- Size
- Build artifact structure (files, schema, manifest)
- File validation (schema, manifest)
- Number of files? (including sub-dirs) - If there's millions of them, but they're small to circumvent the size validation then we could still have an issue

**Comment by nerfZael** [comment]
Moving this to "Need Spec" to better define how the validation should behave

**Comment by nerfZael** [comment]
Blocking: 
- https://github.com/polywrap/nodes/issues/48
- https://github.com/polywrap/nodes/issues/74

**Comment by nerfZael** [comment]
Requesting feedback: @dOrgJelli

**Comment by dOrgJelli** [comment]
This sounds good to me @nerfZael, no specific feedback! Agreed it should live inside of "core".

**Comment by nerfZael** [comment]
First steps:
- Wrapper size maximum
- Wasm module maximum
- Validate all manifests
- Verify no extraneous files (ones not defined in manifest)

**Comment by nerfZael** [comment]
Closed by https://github.com/polywrap/monorepo/pull/933
