### ISSUE TITLE
Question: use Option type from as-container instead of Nullable type that we are using currently

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#809]
Benefits:
- thoroughly tested code
- rust-inspired 
- supports any type to be wrapped in this container primitive unlike our Nullable that just allows the base type to be nullable.
- Similar exp to the Result type since from the same package.

Checkout : https://github.com/yjhmelody/as-container for more info

**Comment by dOrgJelli** [comment]
Yes I agree with this change.

I did not make this change [in the initial PR](https://github.com/polywrap/monorepo/pull/674) because it was "out of scope", but forgot to make an issue for this :P thank you so much for catching this!
