### ISSUE TITLE
docgen refactor: move "react" sub-command to a separate template repo

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#834]
For separation of concerns, the docgen CLI command should to be more focused on markdown generation. Let's move the docusaurus react app template out of the monorepo and into its own repo, and remove the "react" subcommand.

**Comment by krisbitney** [comment]
I think it makes sense to close this issue and not move forward with it. It's very easy to create a docusaurus site with the generated markdown. The newer versions of docusaurus even automate the sidebar based on folder structure.

**Comment by dOrgJelli** [comment]
Amazing @krisbitney, sounds great!
