### ISSUE TITLE
I want to define custom named modules, and not be constrained to using "Query" and "Mutation"

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/prototype#835]
# Description
Today, users are restricted to programming their wrapper's logic into 2 different Wasm modules: `query.wasm` and `mutation.wasm`

This is because in the schema interface layer, we are abiding by standard GraphQL best practices, and exposing all executable methods via the `Query` and `Mutation` types.

Based on prior considerations, we are moving farther away from GraphQL (more information [here](https://forum.polywrap.io/t/graphql-is-it-hindering-developer-experience/130)), so it only makes sense to also allow developers to name their own custom modules.

# Planning
Based on @krisbitney's recent feedback shared within the DAO sync, one of the major pain points of building the Uniswap wrapper was not being able to group Wasm logic logically, and instead needing to do it based on query & mutation.

After having a call with @evanjacobs, @nerfZael, and @krisbitney, we've concluded that this would be great to have for the initial release since it is a large breaking change.

An initial brainstorm of the impact & implementation details can be found here:
https://hackmd.io/p6Czce10R3WoEyfpDMo_kA?view

# General Implementation Steps
> This section is still WIP, will add sub-tasks soon

1. Schema Parse
- Call `TypeInfo` something else like `ModuleTypeInfo`
- Reword the concept of "environments", removing the shared environment option

2. Schema Compose
- Rework the composition algorithm to deal with single modules, instead of collections 

3. Schema Bind
- Update templates

4. Update Wrapper Artifacts

5. Core/Client Updates?

6. CLI Updates?

# Time Estimates
```
{
  schema_parse: 15-20,
  parallel: {
    schema_compose: 10-15,
    schema_bind: 5,
  }
  client: 5,
  cli: 5,
  plugins: 5,
  parallel: {
    demos: 2,
    integrations: 5,
    docs: 4
  }
}

total = 45-55
```

**Comment by evanjacobs** [comment]
TODO: specify sub-tasks for this story

**Comment by cbrzn** [comment]
My thoughts on how to tackle this: https://hackmd.io/hlexOKodQzWAnWV9eABuMw

**Comment by cbrzn** [comment]
Notes from chat with Nestor & Jordan: https://hackmd.io/7MilyOKFSiKOxQXRJVlQBQ#Parts

**Comment by namesty** [comment]
Guys, after several rounds of discussion, the definition of what this story entails, and how we should approach the implementation of this, has changed considerably, so I'm closing this, in favor of this new story: #886
