### ISSUE TITLE
convert legacy Promise.then.catch syntax into async...await...

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#858]

**Comment by dOrgJelli** [comment]
@Niraj-Kamdar can you clarify what you mean by this?

**Comment by Niraj-Kamdar** [comment]
We are using `Promise.then` at some places and since we use `async..await` semantics mostly, it looks out of place. It would be nice to stick to one pattern if possible.

**Comment by krisbitney** [comment]
Do we still want to do this? I don't think promise callbacks are deprecated or anything.

**Comment by dOrgJelli** [comment]
Yah I think this is fine, no need to change existing code that's functional, just for stylistic reasons. Would hate to introduce a hard to reproduce concurrency-related bug.
