### ISSUE TITLE
Add tests for CLI create command

### ISSUE THREAD

**Issue by pileks** [Web3-API/prototype#907]
PR https://github.com/polywrap/monorepo/pull/902 fixed a bug where the refactor to Commander introduced issues with the `name` argument in the `create` command.

We should add unit/integration tests to confirm that the CLI commands work as expected in terms of accepting appropriate arguments and produce expected outputs based on the same arguments.

**Comment by cbrzn** [comment]
This task should be converted into unit tests for the entire CLI and not only the create command. I will push this once the alpha sprint is over :-).

More context of my thoughts on this here https://github.com/polywrap/monorepo/pull/959#pullrequestreview-1018552141

**Comment by dOrgJelli** [comment]
Closing this as we now fully test the `create` command, but as @cbrzn has suggested we should create more unit tests for the CLI in general to increase our code coverage.
