### ISSUE TITLE
remove redundant config option from build manifest

### ISSUE THREAD

**Issue by fetsorn** [Web3-API/prototype#929]
“buildxOutput” in the build manifest can be either “string” or “boolean”. 

When it is a string it overrides the output path. But when it is a boolean it defaults to “docker” on both “true” and “false”. 

It should be just “string” and default to “docker” when unset.

https://github.com/polywrap/monorepo/blob/abe4e902983c1bce292ff5fe3f1a32447040b301/packages/manifest-schemas/formats/polywrap.build/0.0.1-prealpha.3.json#L35-L37

https://github.com/polywrap/monorepo/blob/abe4e902983c1bce292ff5fe3f1a32447040b301/packages/cli/src/lib/Compiler.ts#L315-L319

https://github.com/polywrap/monorepo/blob/abe4e902983c1bce292ff5fe3f1a32447040b301/packages/cli/src/lib/system/docker.ts#L134-L136

**Comment by dOrgJelli** [comment]
Great find @fetsorn. It looks like this feature isn't fully implemented, and it only supports two `--output` options: `docker`, and `registry`.

I think we should remove this for now, and re-add it fully when the need arrives.
