### ISSUE TITLE
add manifest schema for workflow file

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Web3-API/prototype#970]

**Comment by fetsorn** [comment]
Right now we are expecting the workflow file to be valid, and we use the Workflow type provided in core-js. We should add support for workflow files to @polywrap/polywrap-manifest-schemas and @polywrap/polywrap-manifest-types-js, and the Workflow type should be imported similar to DeployManifest and InfraManifest.
This would validate the workflow file against a json schema, and allow for future migrations of workflow files.
