### ISSUE TITLE
Improve Workflows exceptions and result messages

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#984]
While the Workflows seem to work as expected, the CLI run command does not currently output helpful messages when things go wrong or right. For example, `undefined` is printed to the console when a job fails validation. Users are not informed which job failed or why.

We need:

- [x] https://github.com/polywrap/monorepo/issues/1151
- [x] Print an informative error message when workflow validation fails due to an error in validator file syntax
- [x] https://github.com/polywrap/monorepo/issues/1150
- [x] https://github.com/polywrap/monorepo/issues/1149
- [x] An indication that a workflow has run successfully
- [x] https://github.com/polywrap/monorepo/issues/1148

Additional proposal:
Ideally, we would also add a verbose parameter. Some packages have a verbose option to vaguely indicate how much output to expect. Valid values could be like 0, 1, or 2.

0 -> quiet
1 - > minimal output. For workflows, I'm thinking it would print the job status and job id for each job, but suppress the output values
2 -> full output

**Comment by dOrgJelli** [comment]
Hey @krisbitney, can you please provide a list of sub-tasks here, so that we may see how close this is to complete?
