### ISSUE TITLE
JavaScript minimization (aka "minification")

### ISSUE THREAD

**Issue by krisbitney** [Web3-API/prototype#985]
JavaScript minimization (aka "minification") issues have been encountered in both the Uniswap v3 front end demo and the Polywrap Hub. For example, in the Polywrap Hub, class names were being erased during optimization and this was fixed by configuring Webpack. We should ensure our JavaScript packages comply with minimization standards/requirements so that minimization works without requiring users to modify Webpack settings.

**Comment by dOrgJelli** [comment]
Can we do some research on:
- reproducing these minifcation errors (branch links w/ repro steps)
- what are some common issues with minification in production are ([removing class names](https://duckduckgo.com/?q=minification+removing+class+names&t=brave&ia=web) for example)
- where in our code are these issue stemming from?

**Comment by cbrzn** [comment]
> reproducing these minifcation errors (branch links w/ repro steps)
- Go to demos repository & checkout to branch `update-hello-world-to-origin` (PR: https://github.com/polywrap/demos/pull/70)
- In `ts-vanilla` app, go to the `webpack.config.js` file and change (in line 5) mode to `production`
- Run the app and try to run the invocation - it should fail

> where in our code are these issue stemming from?

Based on @Brioline report of the bug, it looks like the `Uri` class might be a problem regarding minification. My first thought is that it is something with the `getters` but not sure...
![image](https://user-images.githubusercontent.com/21031138/179001199-7af0430e-d4fd-4148-ba2e-0cdbf29bf71f.png)

Also, it's worth mentioning that I fixed this with the keep function & class names in minification (https://github.com/polywrap/polyfolio/pull/150/files)
